// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function AddProspectModal({ v }: { v: VM }) {
  return (
    <>
      <div
        style={{
          position: "fixed",
          inset: "0",
          background: "rgba(12,18,32,.55)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          zIndex: "100",
        }}
      >
        <div
          style={{
            background: "#fff",
            borderRadius: "8px",
            width: "560px",
            maxHeight: "86vh",
            overflowY: "auto",
            padding: "24px 26px",
          }}
        >
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
            <div style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "20px", fontWeight: "600" }}>
              Add prospect
            </div>
            <div
              onClick={v.closeAdd}
              style={{ fontSize: "13px", color: "#8a8474", cursor: "pointer" }}
              className="hover-color-10151e"
            >
              Close ×
            </div>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px", marginTop: "18px" }}>
            {v.addFields?.map((f, i) => (
              <div key={i} style={{ gridColumn: f.span }}>
                <div
                  style={{
                    fontSize: "10.5px",
                    letterSpacing: ".1em",
                    textTransform: "uppercase",
                    color: "#8a8474",
                    fontWeight: "600",
                    marginBottom: "5px",
                  }}
                >
                  {f.label}
                </div>
                <input
                  value={f.val}
                  onChange={f.on}
                  placeholder={f.ph}
                  style={{
                    width: "100%",
                    boxSizing: "border-box",
                    border: "1px solid #e6e2d8",
                    borderRadius: "4px",
                    padding: "8px 11px",
                    fontSize: "13px",
                    background: "#faf9f5",
                    color: "#10151e",
                    outline: "none",
                  }}
                />
              </div>
            ))}
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "600",
                  marginBottom: "5px",
                }}
              >
                Industry
              </div>
              <select
                value={v.addIndustry}
                onChange={v.setAddIndustry}
                style={{
                  width: "100%",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "8px 10px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                }}
              >
                {v.industryOpts?.map((o, i) => (
                  <option key={i} value={o}>
                    {o}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "600",
                  marginBottom: "5px",
                }}
              >
                Lead source
              </div>
              <select
                value={v.addSource}
                onChange={v.setAddSource}
                style={{
                  width: "100%",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "8px 10px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                }}
              >
                {v.sourceOpts?.map((o, i) => (
                  <option key={i} value={o}>
                    {o}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <div style={{ fontSize: "11.5px", color: "#8a8474", marginTop: "14px" }}>
            New prospects start in <b>New</b> with next action “Research decision-maker” due today.
          </div>
          {v.hasAddError ? (
            <div
              style={{
                background: "#f6e6e4",
                border: "1px solid #e3c3bf",
                borderRadius: "4px",
                padding: "9px 12px",
                marginTop: "12px",
                fontSize: "12.5px",
                color: "#8a3b34",
                fontWeight: "600",
              }}
            >
              {v.addError}
            </div>
          ) : null}
          <div style={{ display: "flex", gap: "10px", justifyContent: "flex-end", marginTop: "18px" }}>
            <button
              onClick={v.closeAdd}
              style={{
                border: "1px solid #e6e2d8",
                background: "#fff",
                borderRadius: "4px",
                padding: "9px 16px",
                fontSize: "13px",
                cursor: "pointer",
                color: "#3a3f48",
              }}
            >
              Cancel
            </button>
            <button
              onClick={v.saveAdd}
              style={{
                background: "#0c1220",
                color: "#fff",
                border: "none",
                borderRadius: "4px",
                padding: "9px 18px",
                fontSize: "13px",
                fontWeight: "500",
                cursor: "pointer",
              }}
              className="hover-bg-a8863d"
            >
              Save prospect
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
