// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function AnalyticsView({ v }: { v: VM }) {
  return (
    <>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "14px" }}>
        {v.anGroups?.map((g, i) => (
          <div
            key={i}
            style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "16px 18px" }}
          >
            <div
              style={{
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#a8863d",
                fontWeight: "600",
              }}
            >
              {g.label}
            </div>
            {g.rows?.map((r, i) => (
              <div
                key={i}
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "baseline",
                  padding: "8px 0",
                  borderBottom: "1px solid #f0ede4",
                }}
              >
                <span style={{ fontSize: "12.5px", color: "#6b6f78" }}>{r.k}</span>
                <span style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "16px", fontWeight: "600" }}>
                  {r.v}
                </span>
              </div>
            ))}
          </div>
        ))}
      </div>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1.2fr 1fr",
          gap: "14px",
          marginTop: "16px",
          alignItems: "start",
        }}
      >
        <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "16px 18px" }}>
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Acquisition performance
          </div>
          {v.acqPerf?.map((r, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                justifyContent: "space-between",
                gap: "16px",
                alignItems: "baseline",
                padding: "8px 0",
                borderBottom: "1px solid #f0ede4",
              }}
            >
              <span style={{ fontSize: "12.5px", color: "#6b6f78" }}>{r.k}</span>
              <span style={{ fontSize: "13px", fontWeight: "600", textAlign: "right" }}>{r.v}</span>
            </div>
          ))}
        </div>
        <div style={{ background: "#0c1220", borderRadius: "6px", padding: "16px 18px", color: "#fff" }}>
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            What predicts a win?
          </div>
          {v.predictors?.map((p, i) => (
            <div key={i} style={{ padding: "10px 0", borderBottom: "1px solid rgba(255,255,255,.1)" }}>
              <div
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "rgba(255,255,255,.5)",
                  fontWeight: "700",
                }}
              >
                {p.k}
              </div>
              <div style={{ fontSize: "13px", marginTop: "4px" }}>{p.v}</div>
            </div>
          ))}
          <div style={{ fontSize: "11px", color: "rgba(255,255,255,.4)", marginTop: "10px" }}>
            Conclusions are withheld where the sample is too small. No fabricated patterns.
          </div>
        </div>
      </div>
      <div
        style={{
          background: "#fff",
          border: "1px solid #e6e2d8",
          borderRadius: "6px",
          marginTop: "16px",
          padding: "16px 20px",
        }}
      >
        <div
          style={{
            fontSize: "10.5px",
            letterSpacing: ".12em",
            textTransform: "uppercase",
            color: "#a8863d",
            fontWeight: "600",
          }}
        >
          Stage conversion
        </div>
        {v.convFunnel?.map((f, i) => (
          <div key={i} style={{ display: "flex", alignItems: "center", gap: "14px", padding: "7px 0" }}>
            <span style={{ width: "110px", fontSize: "12.5px", color: "#3a3f48", flex: "none" }}>{f.stage}</span>
            <div
              style={{ flex: "1", background: "#f0ede4", borderRadius: "3px", height: "20px", position: "relative" }}
            >
              <div
                style={{
                  position: "absolute",
                  left: "0",
                  top: "0",
                  bottom: "0",
                  width: f.w,
                  background: "#0c1220",
                  borderRadius: "3px",
                }}
              />
            </div>
            <span
              style={{
                width: "34px",
                fontFamily: "'Source Serif 4',Georgia,serif",
                fontSize: "14px",
                fontWeight: "600",
                textAlign: "right",
                flex: "none",
              }}
            >
              {f.count}
            </span>
            <span style={{ width: "70px", fontSize: "11.5px", color: "#8a8474", textAlign: "right", flex: "none" }}>
              {f.pct}
            </span>
          </div>
        ))}
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "14px", marginTop: "16px" }}>
        {v.breakdowns?.map((bd, i) => (
          <div
            key={i}
            style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "16px 18px" }}
          >
            <div
              style={{
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#a8863d",
                fontWeight: "600",
              }}
            >
              {bd.label}
            </div>
            {bd.rows?.map((r, i) => (
              <div key={i} style={{ padding: "8px 0", borderBottom: "1px solid #f0ede4" }}>
                <div style={{ display: "flex", justifyContent: "space-between", fontSize: "12.5px" }}>
                  <span>{r.k}</span>
                  <span style={{ color: "#8a8474" }}>{r.meta}</span>
                </div>
                <div
                  style={{
                    background: "#f0ede4",
                    borderRadius: "2px",
                    height: "6px",
                    marginTop: "6px",
                    position: "relative",
                  }}
                >
                  <div
                    style={{
                      position: "absolute",
                      left: "0",
                      top: "0",
                      bottom: "0",
                      width: r.w,
                      background: "#a8863d",
                      borderRadius: "2px",
                    }}
                  />
                </div>
              </div>
            ))}
          </div>
        ))}
      </div>
    </>
  );
}
