// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";
import { activate } from "./ui";

export default function ClientsView({ v }: { v: VM }) {
  return (
    <>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "12px", marginBottom: "16px" }}>
        {v.clientStats?.map((s, i) => (
          <div
            key={i}
            style={{ background: "#fff", border: "1px solid #e4e4e7", borderRadius: "12px", padding: "14px 16px" }}
          >
            <div
              style={{
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#73767a",
                fontWeight: "600",
              }}
            >
              {s.label}
            </div>
            <div
              style={{
                fontFamily: "'Archivo',system-ui,sans-serif",
                fontSize: "24px",
                fontWeight: "600",
                marginTop: "6px",
              }}
            >
              {s.value}
            </div>
          </div>
        ))}
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" }}>
        {v.clients?.map((c, i) => (
          <div
            key={i}
            style={{ background: "#fff", border: "1px solid #e4e4e7", borderRadius: "12px", padding: "18px 20px" }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
              <span
                onClick={c.on}
                style={{
                  fontFamily: "'Archivo',system-ui,sans-serif",
                  fontSize: "18px",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                className="hover-color-a8863d"
                role="button"
                tabIndex={0}
                onKeyDown={activate}
              >
                {c.name}
              </span>
              <span
                style={{
                  fontFamily: "'Archivo',system-ui,sans-serif",
                  fontSize: "18px",
                  fontWeight: "600",
                  color: "#2e7d5b",
                }}
              >
                {c.revenue}
              </span>
            </div>
            <div style={{ fontSize: "12px", color: "#73767a", marginTop: "3px" }}>{c.meta}</div>
            <div style={{ display: "flex", gap: "6px", flexWrap: "wrap", marginTop: "10px" }}>
              {c.services?.map((s, i) => (
                <span
                  key={i}
                  style={{
                    fontSize: "11px",
                    background: "#efeff1",
                    color: "#2a2c31",
                    borderRadius: "999px",
                    padding: "3px 8px",
                  }}
                >
                  {s}
                </span>
              ))}
            </div>
            <div style={{ marginTop: "14px", borderTop: "1px solid #efeff1", paddingTop: "12px" }}>
              <div
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#e0176b",
                  fontWeight: "700",
                }}
              >
                Growth opportunities
              </div>
              {c.growth?.map((g, i) => (
                <div key={i} style={{ fontSize: "12.5px", marginTop: "7px", color: "#2a2c31" }}>
                  ↗ {g}
                </div>
              ))}
              <div style={{ fontSize: "11.5px", color: "#73767a", marginTop: "10px" }}>{c.referral}</div>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
