// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function ClientsView({ v }: { v: VM }) {
  return (
    <>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "12px", marginBottom: "16px" }}>
        {v.clientStats?.map((s, i) => (
          <div
            key={i}
            style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "14px 16px" }}
          >
            <div
              style={{
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#8a8474",
                fontWeight: "600",
              }}
            >
              {s.label}
            </div>
            <div
              style={{
                fontFamily: "'Source Serif 4',Georgia,serif",
                fontSize: "24px",
                fontWeight: "600",
                marginTop: "6px",
              }}
            >
              {s.value}
            </div>
          </div>
        ))}
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" }}>
        {v.clients?.map((c, i) => (
          <div
            key={i}
            style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "18px 20px" }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
              <span
                onClick={c.on}
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "18px",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                className="hover-color-a8863d"
              >
                {c.name}
              </span>
              <span
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "18px",
                  fontWeight: "600",
                  color: "#2e7d5b",
                }}
              >
                {c.revenue}
              </span>
            </div>
            <div style={{ fontSize: "12px", color: "#8a8474", marginTop: "3px" }}>{c.meta}</div>
            <div style={{ display: "flex", gap: "6px", flexWrap: "wrap", marginTop: "10px" }}>
              {c.services?.map((s, i) => (
                <span
                  key={i}
                  style={{
                    fontSize: "11px",
                    background: "#f0ede4",
                    color: "#3a3f48",
                    borderRadius: "3px",
                    padding: "3px 8px",
                  }}
                >
                  {s}
                </span>
              ))}
            </div>
            <div style={{ marginTop: "14px", borderTop: "1px solid #f0ede4", paddingTop: "12px" }}>
              <div
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "700",
                }}
              >
                Growth opportunities
              </div>
              {c.growth?.map((g, i) => (
                <div key={i} style={{ fontSize: "12.5px", marginTop: "7px", color: "#3a3f48" }}>
                  ↗ {g}
                </div>
              ))}
              <div style={{ fontSize: "11.5px", color: "#8a8474", marginTop: "10px" }}>{c.referral}</div>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
