// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function CloseOutcomeModal({ v }: { v: VM }) {
  return (
    <>
      <div
        style={{
          position: "fixed",
          inset: "0",
          background: "rgba(12,18,32,.55)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          zIndex: "120",
        }}
      >
        <div
          style={{
            background: "#fff",
            borderRadius: "8px",
            width: "560px",
            maxHeight: "88vh",
            overflowY: "auto",
            padding: "24px 26px",
          }}
        >
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
            <div style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "20px", fontWeight: "600" }}>
              Mark {v.closeKind} · {v.closeCompany}
            </div>
            <div
              onClick={v.closeCloseModal}
              style={{ fontSize: "13px", color: "#8a8474", cursor: "pointer" }}
              className="hover-color-10151e"
            >
              Close ×
            </div>
          </div>
          {v.isLostClose ? (
            <>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                  marginTop: "18px",
                }}
              >
                Reason lost
              </div>
              <div style={{ display: "flex", gap: "7px", flexWrap: "wrap", marginTop: "8px" }}>
                {v.closeReasons?.map((r, i) => (
                  <div
                    key={i}
                    onClick={r.on}
                    style={{
                      fontSize: "12px",
                      padding: "6px 12px",
                      borderRadius: "14px",
                      cursor: "pointer",
                      border: "1px solid #e6e2d8",
                      background: r.bg,
                      color: r.fg,
                    }}
                    className="hover-border-a8863d"
                  >
                    {r.label}
                  </div>
                ))}
              </div>
            </>
          ) : null}
          {v.isWonClose ? (
            <>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                  marginTop: "18px",
                }}
              >
                Final project value (ZAR)
              </div>
              <input
                value={v.closeValue}
                onChange={v.setCloseValue}
                placeholder="e.g. 420000"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "6px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 12px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
              <div style={{ fontSize: "11.5px", color: "#8a8474", marginTop: "6px" }}>
                Service, source, campaign and time to close are captured automatically from the prospect record.
              </div>
            </>
          ) : null}
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
              marginTop: "18px",
            }}
          >
            What happened?
          </div>
          <textarea
            value={v.closeNotes}
            onChange={v.setCloseNotes}
            placeholder="The honest version — it feeds the outcome record."
            style={{
              width: "100%",
              boxSizing: "border-box",
              marginTop: "6px",
              border: "1px solid #e6e2d8",
              borderRadius: "4px",
              padding: "10px 12px",
              fontSize: "13px",
              minHeight: "84px",
              resize: "vertical",
              background: "#faf9f5",
              color: "#10151e",
              outline: "none",
            }}
          />
          <div style={{ display: "flex", gap: "10px", justifyContent: "flex-end", marginTop: "18px" }}>
            <button
              onClick={v.closeCloseModal}
              style={{
                border: "1px solid #e6e2d8",
                background: "#fff",
                borderRadius: "4px",
                padding: "9px 16px",
                fontSize: "13px",
                cursor: "pointer",
                color: "#3a3f48",
              }}
            >
              Cancel
            </button>
            <button
              onClick={v.confirmClose}
              style={{
                background: "#0c1220",
                color: "#fff",
                border: "none",
                borderRadius: "4px",
                padding: "9px 18px",
                fontSize: "13px",
                fontWeight: "600",
                cursor: "pointer",
              }}
              className="hover-bg-a8863d"
            >
              Record outcome
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
