// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";
import { activate } from "./ui";

export default function DashboardView({ v }: { v: VM }) {
  return (
    <>
      <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", marginBottom: "16px" }}>
        <div style={{ fontSize: "13px", color: "#6b6f78" }}>
          What should you do next to get a client — {v.todayLabelReal}
        </div>
        <div style={{ fontSize: "10.5px", letterSpacing: ".12em", textTransform: "uppercase", color: "#a8863d" }}>
          Find → Qualify → Diagnose → Outreach → Discovery → Proposal → Won
        </div>
      </div>
      <div
        style={{
          background: "#0c1220",
          borderRadius: "6px",
          padding: "20px 22px",
          color: "#fff",
          marginBottom: "16px",
        }}
      >
        <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
          <div style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "22px", fontWeight: "600" }}>
            Today’s Acquisition Plan
          </div>
          <div
            style={{
              fontSize: "11px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "700",
            }}
          >
            What to do right now to win a client
          </div>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "12px", marginTop: "16px" }}>
          {v.planCounts?.map((p, i) => (
            <div
              key={i}
              style={{ border: "1px solid rgba(255,255,255,.12)", borderRadius: "5px", padding: "12px 14px" }}
            >
              <div
                style={{
                  fontSize: "10px",
                  letterSpacing: ".12em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "700",
                }}
              >
                {p.label}
              </div>
              <div
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "24px",
                  fontWeight: "600",
                  marginTop: "4px",
                }}
              >
                {p.value}
              </div>
              <div style={{ fontSize: "11px", color: "rgba(255,255,255,.5)" }}>{p.sub}</div>
            </div>
          ))}
        </div>
        <div style={{ display: "flex", gap: "6px", marginTop: "18px", flexWrap: "wrap" }}>
          {v.planTabs?.map((t, i) => (
            <div
              key={i}
              onClick={t.on}
              style={{
                display: "flex",
                alignItems: "center",
                gap: "7px",
                fontSize: "12px",
                padding: "7px 13px",
                borderRadius: "4px",
                cursor: "pointer",
                fontWeight: "600",
                border: `1px solid ${t.border ?? ""}`,
                background: t.bg,
                color: t.fg,
              }}
              role="button"
              tabIndex={0}
              onKeyDown={activate}
            >
              <span>{t.label}</span>
              <span style={{ fontSize: "10.5px", opacity: ".75" }}>{t.n}</span>
            </div>
          ))}
        </div>
        <div style={{ background: "#fff", borderRadius: "5px", marginTop: "12px", overflowX: "auto" }}>
          {v.planRows?.map((p, i) => (
            <div
              key={i}
              onClick={p.on}
              style={{
                display: "grid",
                gridTemplateColumns: "minmax(140px,1.5fr) 96px 70px minmax(130px,1.3fr) minmax(120px,1.6fr) 118px",
                gap: "10px",
                padding: "11px 16px",
                minWidth: "820px",
                borderBottom: "1px solid #f0ede4",
                cursor: "pointer",
                alignItems: "center",
              }}
              className="hover-bg-faf9f5"
              role="button"
              tabIndex={0}
              onKeyDown={activate}
            >
              <span style={{ fontSize: "13.5px", fontWeight: "600", color: "#10151e" }}>{p.name}</span>
              <span style={{ display: "flex", alignItems: "center", gap: "5px" }}>
                <span
                  style={{
                    fontFamily: "'Source Serif 4',Georgia,serif",
                    fontSize: "15px",
                    fontWeight: "600",
                    color: "#10151e",
                  }}
                >
                  {p.acq}
                </span>
                <span
                  style={{
                    fontSize: "9px",
                    letterSpacing: ".05em",
                    textTransform: "uppercase",
                    fontWeight: "700",
                    color: p.bandFg,
                    background: p.bandBg,
                    borderRadius: "3px",
                    padding: "2px 5px",
                  }}
                >
                  {p.band}
                </span>
              </span>
              <span style={{ fontSize: "12px", fontWeight: "600", color: p.readyFg }}>{p.readiness}</span>
              <span>
                <span style={{ display: "block", fontSize: "12.5px", color: "#6b6f78" }}>
                  {p.stage} · {p.value}
                </span>
                <span style={{ display: "block", fontSize: "11.5px", color: "#b0453c", fontWeight: "600" }}>
                  {p.stallLabel}
                </span>
              </span>
              <span style={{ fontSize: "12.5px", color: "#10151e", fontWeight: "500" }}>{p.action}</span>
              <button
                onClick={p.onAction}
                style={{
                  border: "1px solid #0c1220",
                  background: "#0c1220",
                  color: "#fff",
                  borderRadius: "4px",
                  padding: "6px 8px",
                  fontSize: "11px",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                className="hover-bg-a8863d"
              >
                Do it →
              </button>
            </div>
          ))}
          {v.isWaitingTab ? (
            <div style={{ padding: "10px 16px", fontSize: "11.5px", color: "#8a8474", background: "#faf9f5" }}>
              Waiting on:{" "}
              {v.planRows?.map((p, i) => (
                <span key={i} style={{ marginRight: "12px" }}>
                  {p.name} — {p.waitingOn}
                </span>
              ))}
            </div>
          ) : null}
          {v.isRiskTab ? (
            <div style={{ padding: "10px 16px", fontSize: "11.5px", color: "#8a3b34", background: "#f6e6e4" }}>
              Risks:{" "}
              {v.planRows?.map((p, i) => (
                <span key={i} style={{ marginRight: "12px" }}>
                  {p.name} — {p.risk}
                </span>
              ))}
            </div>
          ) : null}
          {v.planEmpty ? (
            <div style={{ padding: "14px 16px", fontSize: "12.5px", color: "#8a8474" }}>{v.planEmptyMsg}</div>
          ) : null}
        </div>
        <div style={{ marginTop: "18px", borderTop: "1px solid rgba(255,255,255,.12)", paddingTop: "14px" }}>
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".14em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "700",
            }}
          >
            Today’s targets
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(6,1fr)", gap: "12px", marginTop: "10px" }}>
            {v.targets?.map((t, i) => (
              <div key={i}>
                <div style={{ display: "flex", justifyContent: "space-between", fontSize: "11px" }}>
                  <span style={{ color: "rgba(255,255,255,.6)" }}>{t.label}</span>
                  <span style={{ fontWeight: "700" }}>{t.text}</span>
                </div>
                <div
                  style={{
                    background: "rgba(255,255,255,.12)",
                    borderRadius: "2px",
                    height: "5px",
                    marginTop: "5px",
                    position: "relative",
                  }}
                >
                  <div
                    style={{
                      position: "absolute",
                      left: "0",
                      top: "0",
                      bottom: "0",
                      width: t.w,
                      background: t.bar,
                      borderRadius: "2px",
                    }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
        <div style={{ marginTop: "18px", borderTop: "1px solid rgba(255,255,255,.12)", paddingTop: "14px" }}>
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".14em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "700",
            }}
          >
            Recommended actions
          </div>
          {v.recommended?.map((r, i) => (
            <div
              key={i}
              onClick={r.on}
              style={{
                display: "flex",
                gap: "12px",
                alignItems: "baseline",
                padding: "8px 0",
                borderBottom: "1px solid rgba(255,255,255,.07)",
                cursor: "pointer",
              }}
              className="hover-color-a8863d"
              role="button"
              tabIndex={0}
              onKeyDown={activate}
            >
              <span
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "14px",
                  color: "#a8863d",
                  width: "20px",
                  flex: "none",
                }}
              >
                {r.n}
              </span>
              <span style={{ flex: "1", fontSize: "14px" }}>{r.text}</span>
              <span style={{ fontSize: "11px", color: "rgba(255,255,255,.45)" }}>{r.why}</span>
            </div>
          ))}
        </div>
      </div>
      <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", marginBottom: "16px" }}>
        <div
          style={{
            padding: "14px 18px",
            borderBottom: "1px solid #f0ede4",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <span
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Top prospects by acquisition score
          </span>
          <span style={{ fontSize: "11.5px", color: "#8a8474" }}>Click a score to see how it was calculated</span>
        </div>
        <div style={{ overflowX: "auto" }}>
          {v.topProspects?.map((p, i) => (
            <div
              key={i}
              onClick={p.on}
              style={{
                display: "grid",
                gridTemplateColumns:
                  "minmax(150px,1.5fr) 132px minmax(150px,1.6fr) 96px minmax(150px,1.5fr) minmax(140px,1.4fr)",
                gap: "12px",
                padding: "12px 18px",
                minWidth: "880px",
                borderBottom: "1px solid #f0ede4",
                cursor: "pointer",
                alignItems: "center",
              }}
              className="hover-bg-faf9f5"
              role="button"
              tabIndex={0}
              onKeyDown={activate}
            >
              <span style={{ fontSize: "14px", fontWeight: "600" }}>{p.name}</span>
              <span
                onClick={p.onScore}
                style={{ display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer" }}
                role="button"
                tabIndex={0}
                onKeyDown={activate}
              >
                <span style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "17px", fontWeight: "600" }}>
                  {p.acq}
                </span>
                <span
                  style={{
                    fontSize: "9.5px",
                    letterSpacing: ".06em",
                    textTransform: "uppercase",
                    fontWeight: "700",
                    color: p.bandFg,
                    background: p.bandBg,
                    borderRadius: "3px",
                    padding: "3px 6px",
                  }}
                >
                  {p.band}
                </span>
              </span>
              <span style={{ fontSize: "12.5px", color: "#6b6f78" }}>{p.opp}</span>
              <span style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "13.5px", fontWeight: "600" }}>
                {p.value}
              </span>
              <span style={{ fontSize: "12.5px", color: p.dmFg }}>{p.dm}</span>
              <span style={{ fontSize: "12.5px", color: p.nextFg }}>{p.next}</span>
            </div>
          ))}
        </div>
      </div>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: "16px",
          marginBottom: "16px",
          alignItems: "start",
        }}
      >
        <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px" }}>
          <div
            style={{
              padding: "14px 18px",
              borderBottom: "1px solid #f0ede4",
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Outreach today
          </div>
          {v.outreachToday?.map((o, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                gap: "12px",
                alignItems: "center",
                padding: "11px 18px",
                borderBottom: "1px solid #f0ede4",
              }}
            >
              <span
                onClick={o.on}
                style={{ flex: "1", cursor: "pointer" }}
                role="button"
                tabIndex={0}
                onKeyDown={activate}
              >
                <span style={{ display: "block", fontSize: "13.5px", fontWeight: "500" }}>{o.company}</span>
                <span style={{ display: "block", fontSize: "12px", color: "#8a8474", marginTop: "2px" }}>
                  {o.detail}
                </span>
              </span>
              <button
                onClick={o.onGen}
                style={{
                  border: "1px solid #0c1220",
                  background: "#0c1220",
                  color: "#fff",
                  borderRadius: "4px",
                  padding: "6px 11px",
                  fontSize: "11.5px",
                  fontWeight: "600",
                  cursor: "pointer",
                  flex: "none",
                }}
                className="hover-bg-a8863d"
              >
                Generate message
              </button>
            </div>
          ))}
          {v.noOutreachToday ? (
            <div style={{ padding: "14px 18px", fontSize: "12.5px", color: "#8a8474" }}>
              No outreach queued for today.
            </div>
          ) : null}
        </div>
        <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px" }}>
          <div
            style={{
              padding: "14px 18px",
              borderBottom: "1px solid #f0ede4",
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Profiles incomplete
          </div>
          {v.researchNeeded?.map((r, i) => (
            <div
              key={i}
              onClick={r.on}
              style={{ padding: "11px 18px", borderBottom: "1px solid #f0ede4", cursor: "pointer" }}
              className="hover-bg-faf9f5"
              role="button"
              tabIndex={0}
              onKeyDown={activate}
            >
              <div style={{ display: "flex", justifyContent: "space-between" }}>
                <span style={{ fontSize: "13.5px", fontWeight: "500" }}>{r.company}</span>
                <span style={{ fontSize: "12px", color: "#8a8474" }}>{r.pct} complete</span>
              </div>
              <div
                style={{
                  background: "#f0ede4",
                  borderRadius: "2px",
                  height: "5px",
                  marginTop: "6px",
                  position: "relative",
                }}
              >
                <div
                  style={{
                    position: "absolute",
                    left: "0",
                    top: "0",
                    bottom: "0",
                    width: r.w,
                    background: "#a8863d",
                    borderRadius: "2px",
                  }}
                />
              </div>
              <div style={{ fontSize: "12px", color: "#8a8474", marginTop: "5px" }}>Missing: {r.missing}</div>
            </div>
          ))}
          {v.noResearch ? (
            <div style={{ padding: "14px 18px", fontSize: "12.5px", color: "#8a8474" }}>
              All active profiles complete.
            </div>
          ) : null}
        </div>
      </div>
      <div
        style={{
          background: "#fff",
          border: "1px solid #e6e2d8",
          borderRadius: "6px",
          marginBottom: "16px",
          overflowX: "auto",
        }}
      >
        <div
          style={{
            padding: "14px 18px",
            borderBottom: "1px solid #f0ede4",
            fontSize: "10.5px",
            letterSpacing: ".12em",
            textTransform: "uppercase",
            color: "#a8863d",
            fontWeight: "600",
          }}
        >
          Revenue opportunities in play
        </div>
        {v.revenueOps?.map((r, i) => (
          <div
            key={i}
            onClick={r.on}
            style={{
              display: "grid",
              gridTemplateColumns: "minmax(150px,1.6fr) minmax(100px,1fr) minmax(150px,1.8fr) 110px 70px",
              gap: "12px",
              minWidth: "760px",
              padding: "11px 18px",
              borderBottom: "1px solid #f0ede4",
              cursor: "pointer",
              alignItems: "center",
            }}
            className="hover-bg-faf9f5"
            role="button"
            tabIndex={0}
            onKeyDown={activate}
          >
            <span style={{ fontSize: "13.5px", fontWeight: "500" }}>{r.company}</span>
            <span
              style={{
                fontSize: "11px",
                border: "1px solid #e6e2d8",
                borderRadius: "3px",
                padding: "3px 8px",
                color: "#3a3f48",
                background: "#faf9f5",
                justifySelf: "start",
              }}
            >
              {r.stage}
            </span>
            <span style={{ fontSize: "12.5px", color: "#6b6f78" }}>{r.opp}</span>
            <span
              style={{
                fontFamily: "'Source Serif 4',Georgia,serif",
                fontSize: "14px",
                fontWeight: "600",
                textAlign: "right",
              }}
            >
              {r.value}
            </span>
            <span style={{ fontSize: "12px", color: "#8a8474", textAlign: "right" }}>acq {r.acq}</span>
          </div>
        ))}
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "12px" }}>
        {v.kpis?.map((k, i) => (
          <div
            key={i}
            data-click="1"
            onClick={k.on}
            style={{
              background: "#fff",
              border: "1px solid #e6e2d8",
              borderRadius: "6px",
              padding: "14px 16px",
              cursor: "pointer",
            }}
            className="hover-border-a8863d"
            role="button"
            tabIndex={0}
            onKeyDown={activate}
          >
            <div
              style={{
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#8a8474",
                fontWeight: "600",
              }}
            >
              {k.label}
            </div>
            <div
              style={{
                fontFamily: "'Source Serif 4',Georgia,serif",
                fontSize: "26px",
                fontWeight: "600",
                marginTop: "6px",
              }}
            >
              {k.value}
            </div>
            <div style={{ fontSize: "11.5px", color: "#8a8474", marginTop: "2px" }}>{k.sub}</div>
          </div>
        ))}
      </div>
      <div
        style={{
          background: "#fff",
          border: "1px solid #e6e2d8",
          borderRadius: "6px",
          marginTop: "16px",
          padding: "16px 18px",
        }}
      >
        <div
          style={{
            fontSize: "10.5px",
            letterSpacing: ".12em",
            textTransform: "uppercase",
            color: "#a8863d",
            fontWeight: "600",
          }}
        >
          Acquisition pipeline
        </div>
        <div style={{ display: "flex", gap: "6px", marginTop: "14px" }}>
          {v.funnelStages?.map((s, i) => (
            <div
              key={i}
              onClick={s.on}
              style={{
                flex: "1",
                textAlign: "center",
                padding: "10px 4px",
                borderRadius: "4px",
                cursor: "pointer",
                background: s.bg,
                border: `1px solid ${s.border ?? ""}`,
              }}
              className="hover-border-a8863d"
              role="button"
              tabIndex={0}
              onKeyDown={activate}
            >
              <div
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "20px",
                  fontWeight: "600",
                  color: s.fg,
                }}
              >
                {s.count}
              </div>
              <div
                style={{
                  fontSize: "10px",
                  letterSpacing: ".08em",
                  textTransform: "uppercase",
                  color: s.sub,
                  marginTop: "3px",
                }}
              >
                {s.name}
              </div>
            </div>
          ))}
        </div>
      </div>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1.5fr 1fr",
          gap: "16px",
          marginTop: "16px",
          alignItems: "start",
        }}
      >
        <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
          <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px" }}>
            <div
              style={{
                padding: "14px 18px",
                borderBottom: "1px solid #f0ede4",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
              }}
            >
              <span
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".12em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "600",
                }}
              >
                Today’s actions
              </span>
              <span style={{ fontSize: "11.5px", color: "#8a8474" }}>{v.actionCount} items</span>
            </div>
            {v.actions?.map((a, i) => (
              <div
                key={i}
                onClick={a.on}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                  padding: "11px 18px",
                  borderBottom: "1px solid #f0ede4",
                  cursor: "pointer",
                }}
                className="hover-bg-faf9f5"
                role="button"
                tabIndex={0}
                onKeyDown={activate}
              >
                <span
                  style={{
                    fontSize: "9.5px",
                    letterSpacing: ".1em",
                    textTransform: "uppercase",
                    fontWeight: "700",
                    color: a.tagFg,
                    background: a.tagBg,
                    borderRadius: "3px",
                    padding: "3px 7px",
                    flex: "none",
                    width: "74px",
                    textAlign: "center",
                  }}
                >
                  {a.tag}
                </span>
                <span style={{ fontSize: "13.5px", flex: "1" }}>{a.text}</span>
                <span style={{ fontSize: "12px", color: "#8a8474" }}>{a.company}</span>
                <span style={{ color: "#a8863d", fontSize: "13px" }}>→</span>
              </div>
            ))}
          </div>
          <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px" }}>
            <div
              style={{
                padding: "14px 18px",
                borderBottom: "1px solid #f0ede4",
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#a8863d",
                fontWeight: "600",
              }}
            >
              Priority prospects
            </div>
            {v.priority?.map((p, i) => (
              <div
                key={i}
                onClick={p.on}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                  padding: "11px 18px",
                  borderBottom: "1px solid #f0ede4",
                  cursor: "pointer",
                }}
                className="hover-bg-faf9f5"
                role="button"
                tabIndex={0}
                onKeyDown={activate}
              >
                <span
                  style={{
                    width: "26px",
                    height: "26px",
                    borderRadius: "3px",
                    background: p.gradeBg,
                    color: p.gradeFg,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    fontSize: "12px",
                    fontWeight: "700",
                    flex: "none",
                  }}
                >
                  {p.grade}
                </span>
                <span style={{ flex: "1", minWidth: "0" }}>
                  {" "}
                  <span style={{ display: "block", fontSize: "13.5px", fontWeight: "500" }}>{p.name}</span>{" "}
                  <span style={{ display: "block", fontSize: "11.5px", color: "#8a8474", marginTop: "1px" }}>
                    {p.meta}
                  </span>{" "}
                </span>
                <span style={{ fontSize: "12px", color: "#6b6f78", textAlign: "right" }}>{p.next}</span>
                <span
                  style={{
                    fontFamily: "'Source Serif 4',Georgia,serif",
                    fontSize: "14px",
                    fontWeight: "600",
                    width: "88px",
                    textAlign: "right",
                  }}
                >
                  {p.value}
                </span>
              </div>
            ))}
          </div>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
          <div style={{ background: "#0c1220", borderRadius: "6px", color: "#e8e6e0", padding: "16px 18px" }}>
            <div
              style={{
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#a8863d",
                fontWeight: "600",
              }}
            >
              Pipeline forecast
            </div>
            {v.forecast?.map((f, i) => (
              <div
                key={i}
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "baseline",
                  padding: "10px 0",
                  borderBottom: "1px solid rgba(255,255,255,.08)",
                }}
              >
                <span style={{ fontSize: "12.5px", color: "rgba(255,255,255,.65)" }}>{f.label}</span>
                <span
                  style={{
                    fontFamily: "'Source Serif 4',Georgia,serif",
                    fontSize: "19px",
                    fontWeight: "600",
                    color: "#fff",
                  }}
                >
                  {f.value}
                </span>
              </div>
            ))}
            <div style={{ fontSize: "11px", color: "rgba(255,255,255,.4)", marginTop: "10px" }}>
              Weighted = proposal value × probability
            </div>
          </div>
          <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px" }}>
            <div
              style={{
                padding: "14px 18px",
                borderBottom: "1px solid #f0ede4",
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#a8863d",
                fontWeight: "600",
              }}
            >
              Recent activity
            </div>
            {v.activity?.map((ac, i) => (
              <div key={i} style={{ padding: "10px 18px", borderBottom: "1px solid #f0ede4" }}>
                <div style={{ display: "flex", justifyContent: "space-between" }}>
                  <span
                    style={{
                      fontSize: "10px",
                      letterSpacing: ".1em",
                      textTransform: "uppercase",
                      color: "#8a8474",
                      fontWeight: "600",
                    }}
                  >
                    {ac.kind}
                  </span>
                  <span style={{ fontSize: "11px", color: "#a39d8f" }}>{ac.when}</span>
                </div>
                <div style={{ fontSize: "12.5px", marginTop: "3px", color: "#3a3f48" }}>{ac.text}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}
