// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function DetailOpportunity({ v }: { v: VM }) {
  return (
    <>
      <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "18px 20px" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <span
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Opportunities
          </span>
          <button
            onClick={v.sel?.onAddOpp}
            style={{
              background: "#0c1220",
              color: "#fff",
              border: "none",
              borderRadius: "4px",
              padding: "8px 14px",
              fontSize: "12px",
              fontWeight: "600",
              cursor: "pointer",
            }}
            className="hover-bg-a8863d"
          >
            Identify opportunity →
          </button>
        </div>
        {v.sel?.oppCards?.map((o, i) => (
          <div
            key={i}
            style={{ border: "1px solid #e6e2d8", borderRadius: "5px", padding: "14px 16px", marginTop: "12px" }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
              <span style={{ fontSize: "14px", fontWeight: "600" }}>{o.type}</span>
              <span style={{ display: "flex", gap: "10px", alignItems: "baseline" }}>
                <span
                  style={{
                    fontSize: "10px",
                    letterSpacing: ".06em",
                    textTransform: "uppercase",
                    fontWeight: "700",
                    color: o.quadFg,
                  }}
                >
                  {o.quad}
                </span>
                <span style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "15px", fontWeight: "600" }}>
                  {o.value}
                </span>
              </span>
            </div>
            <div style={{ fontSize: "13px", color: "#3a3f48", marginTop: "6px", lineHeight: "1.5" }}>{o.text}</div>
            <div style={{ display: "flex", gap: "16px", marginTop: "8px", fontSize: "11.5px", color: "#8a8474" }}>
              <span>{o.group}</span>
              <span>Opportunity score {o.score}</span>
              <span>Complexity {o.complexity}</span>
            </div>
            <div style={{ display: "flex", gap: "8px", marginTop: "12px" }}>
              <button
                onClick={o.onStrategy}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "6px 12px",
                  fontSize: "11.5px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
                className="hover-bg-f6f4ef"
              >
                Create strategy →
              </button>
              <button
                onClick={o.onOutreach}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "6px 12px",
                  fontSize: "11.5px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
                className="hover-bg-f6f4ef"
              >
                Generate outreach →
              </button>
            </div>
          </div>
        ))}
        {v.sel?.noOpps ? (
          <div style={{ fontSize: "13px", color: "#8a8474", marginTop: "12px" }}>
            No opportunity recorded yet. Use the digital assessment findings to name the commercial opportunity and size
            it.
          </div>
        ) : null}
        {v.sel?.editingOpp ? (
          <div
            style={{
              borderTop: "1px solid #f0ede4",
              marginTop: "16px",
              paddingTop: "14px",
              display: "grid",
              gridTemplateColumns: "1fr 1fr",
              gap: "12px",
            }}
          >
            <div style={{ gridColumn: "span 2" }}>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Opportunity type <span style={{ color: "#b0453c" }}>Required</span>
              </div>
              <select
                value={v.sel?.oType?.val}
                onChange={v.sel?.oType?.on}
                style={{
                  width: "100%",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 10px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                }}
              >
                <option value="">Choose a type…</option>{" "}
                {v.sel?.oppTypeOpts?.map((t, i) => (
                  <option key={i} value={t}>
                    {t}
                  </option>
                ))}
              </select>
            </div>
            <div style={{ gridColumn: "span 2" }}>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Opportunity <span style={{ color: "#b0453c" }}>Required</span>
              </div>
              <textarea
                value={v.sel?.oText?.val}
                onChange={v.sel?.oText?.on}
                placeholder="What would AX-Channels build, and what does it fix?"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "10px 12px",
                  fontSize: "13px",
                  minHeight: "64px",
                  resize: "vertical",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Estimated value (ZAR)
              </div>
              <input
                value={v.sel?.oValue?.val}
                onChange={v.sel?.oValue?.on}
                placeholder="180000"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 12px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Implementation complexity
              </div>
              <select
                value={v.sel?.oComplexity?.val}
                onChange={v.sel?.oComplexity?.on}
                style={{
                  width: "100%",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 10px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                }}
              >
                <option value="Low">Low</option>
                <option value="High">High</option>
              </select>
            </div>
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Problems (comma separated)
              </div>
              <input
                value={v.sel?.oProblems?.val}
                onChange={v.sel?.oProblems?.on}
                placeholder="No customer portal, Manual process"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 12px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div style={{ display: "flex", gap: "8px", alignItems: "flex-end" }}>
              <span style={{ flex: "1" }}>
                <span
                  style={{
                    display: "block",
                    fontSize: "10.5px",
                    letterSpacing: ".1em",
                    textTransform: "uppercase",
                    color: "#8a8474",
                    fontWeight: "700",
                  }}
                >
                  Impact 1–5
                </span>
                <input
                  value={v.sel?.oImpact?.val}
                  onChange={v.sel?.oImpact?.on}
                  style={{
                    width: "100%",
                    boxSizing: "border-box",
                    marginTop: "5px",
                    border: "1px solid #e6e2d8",
                    borderRadius: "4px",
                    padding: "9px 12px",
                    fontSize: "13px",
                    background: "#faf9f5",
                    color: "#10151e",
                    outline: "none",
                  }}
                />
              </span>
              <span style={{ flex: "1" }}>
                <span
                  style={{
                    display: "block",
                    fontSize: "10.5px",
                    letterSpacing: ".1em",
                    textTransform: "uppercase",
                    color: "#8a8474",
                    fontWeight: "700",
                  }}
                >
                  Fit 1–5
                </span>
                <input
                  value={v.sel?.oFit?.val}
                  onChange={v.sel?.oFit?.on}
                  style={{
                    width: "100%",
                    boxSizing: "border-box",
                    marginTop: "5px",
                    border: "1px solid #e6e2d8",
                    borderRadius: "4px",
                    padding: "9px 12px",
                    fontSize: "13px",
                    background: "#faf9f5",
                    color: "#10151e",
                    outline: "none",
                  }}
                />
              </span>
            </div>
            <div style={{ gridColumn: "span 2", display: "flex", gap: "10px", justifyContent: "flex-end" }}>
              <button
                onClick={v.sel?.onCancelEdit}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "9px 16px",
                  fontSize: "12.5px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
              >
                Cancel
              </button>
              <button
                onClick={v.sel?.onSaveOpp}
                style={{
                  background: "#0c1220",
                  color: "#fff",
                  border: "none",
                  borderRadius: "4px",
                  padding: "9px 18px",
                  fontSize: "12.5px",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                className="hover-bg-a8863d"
              >
                Save opportunity
              </button>
            </div>
          </div>
        ) : null}
      </div>
    </>
  );
}
