// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function DetailDiscovery({ v }: { v: VM }) {
  return (
    <>
      <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "16px 20px" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <span
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Discovery
          </span>
          <span style={{ display: "flex", gap: "8px" }}>
            <button
              onClick={v.sel?.onScheduleMeeting}
              style={{
                background: "#0c1220",
                color: "#fff",
                border: "none",
                borderRadius: "4px",
                padding: "7px 13px",
                fontSize: "11.5px",
                fontWeight: "600",
                cursor: "pointer",
              }}
              className="hover-bg-a8863d"
            >
              Schedule discovery →
            </button>
            <button
              onClick={v.sel?.onRecordMeeting}
              style={{
                border: "1px solid #e6e2d8",
                background: "#fff",
                borderRadius: "4px",
                padding: "7px 13px",
                fontSize: "11.5px",
                cursor: "pointer",
                color: "#3a3f48",
              }}
              className="hover-bg-f6f4ef"
            >
              Record as held
            </button>
            <button
              onClick={v.sel?.onMoveToProposal}
              style={{
                border: "1px solid #e6e2d8",
                background: "#fff",
                borderRadius: "4px",
                padding: "7px 13px",
                fontSize: "11.5px",
                cursor: "pointer",
                color: "#3a3f48",
              }}
              className="hover-bg-f6f4ef"
            >
              Move to proposal →
            </button>
          </span>
        </div>
        {v.sel?.meetingRows?.map((m, i) => (
          <div key={i} style={{ borderTop: "1px solid #f0ede4", marginTop: "12px", paddingTop: "12px" }}>
            <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
              <span style={{ fontSize: "13px", fontWeight: "600" }}>{m.type}</span>
              <span style={{ fontSize: "12.5px", color: "#6b6f78" }}>
                {m.date} · {m.time}
              </span>
              <span style={{ flex: "1" }} />
              <button
                onClick={m.onNotes}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "5px 10px",
                  fontSize: "11px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
                className="hover-bg-f6f4ef"
              >
                Add notes
              </button>
            </div>
            <div style={{ fontSize: "12.5px", color: "#3a3f48", marginTop: "5px" }}>{m.notes}</div>
          </div>
        ))}
        {v.sel?.noMeetings ? (
          <div style={{ fontSize: "13px", color: "#8a8474", marginTop: "12px" }}>
            No discovery booked yet. Schedule one while the reply is warm.
          </div>
        ) : null}
        {v.sel?.editingMeeting ? (
          <div
            style={{
              borderTop: "1px solid #f0ede4",
              marginTop: "14px",
              paddingTop: "14px",
              display: "grid",
              gridTemplateColumns: "1fr 1fr",
              gap: "12px",
            }}
          >
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Date <span style={{ color: "#b0453c" }}>Required</span>
              </div>
              <input
                type="date"
                value={v.sel?.mDate?.val}
                onChange={v.sel?.mDate?.on}
                min={v.today}
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 12px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Time
              </div>
              <input
                value={v.sel?.mTime?.val}
                onChange={v.sel?.mTime?.on}
                placeholder="10:00"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 12px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div style={{ gridColumn: "span 2" }}>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Notes / agenda
              </div>
              <textarea
                value={v.sel?.mNotes?.val}
                onChange={v.sel?.mNotes?.on}
                placeholder="What must this meeting establish?"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "10px 12px",
                  fontSize: "13px",
                  minHeight: "64px",
                  resize: "vertical",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div style={{ gridColumn: "span 2", display: "flex", gap: "10px", justifyContent: "flex-end" }}>
              <button
                onClick={v.sel?.onCancelEdit}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "9px 16px",
                  fontSize: "12.5px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
              >
                Cancel
              </button>
              <button
                onClick={v.sel?.onSaveMeeting}
                style={{
                  background: "#0c1220",
                  color: "#fff",
                  border: "none",
                  borderRadius: "4px",
                  padding: "9px 18px",
                  fontSize: "12.5px",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                className="hover-bg-a8863d"
              >
                Save meeting
              </button>
            </div>
          </div>
        ) : null}
      </div>
    </>
  );
}
