// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function DetailOutcome({ v }: { v: VM }) {
  return (
    <>
      <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "16px 20px" }}>
        <div
          style={{
            fontSize: "10.5px",
            letterSpacing: ".12em",
            textTransform: "uppercase",
            color: "#a8863d",
            fontWeight: "600",
          }}
        >
          Record the outcome
        </div>
        <div style={{ fontSize: "13px", color: "#6b6f78", marginTop: "6px" }}>
          Won captures final value, service, source, campaign and time to close. Lost captures the reason and notes.
          Both write a structured outcome record.
        </div>
        {v.sel?.canClose ? (
          <div style={{ display: "flex", gap: "8px", marginTop: "14px" }}>
            <button
              onClick={v.sel?.onMarkWon}
              style={{
                border: "1px solid #2e7d5b",
                background: "#fff",
                color: "#2e7d5b",
                borderRadius: "4px",
                padding: "9px 16px",
                fontSize: "12.5px",
                fontWeight: "600",
                cursor: "pointer",
              }}
              className="hover-bg-e8f2ec"
            >
              Mark won →
            </button>
            <button
              onClick={v.sel?.onMarkLost}
              style={{
                border: "1px solid #e6e2d8",
                background: "#fff",
                color: "#8a8474",
                borderRadius: "4px",
                padding: "9px 16px",
                fontSize: "12.5px",
                cursor: "pointer",
              }}
              className="hover-bg-f6e6e4-color-8a3b34"
            >
              Mark lost →
            </button>
          </div>
        ) : null}
      </div>
    </>
  );
}
