// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function DetailProposal({ v }: { v: VM }) {
  return (
    <>
      <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "16px 20px" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <span
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Proposals
          </span>
          <button
            onClick={v.sel?.onCreateProposal}
            style={{
              background: "#0c1220",
              color: "#fff",
              border: "none",
              borderRadius: "4px",
              padding: "7px 13px",
              fontSize: "11.5px",
              fontWeight: "600",
              cursor: "pointer",
            }}
            className="hover-bg-a8863d"
          >
            Create proposal →
          </button>
        </div>
        {v.sel?.proposalRows?.map((p, i) => (
          <div key={i} style={{ borderTop: "1px solid #f0ede4", marginTop: "12px", paddingTop: "12px" }}>
            <div style={{ display: "flex", gap: "12px", alignItems: "baseline", flexWrap: "wrap" }}>
              <span style={{ fontSize: "13.5px", fontWeight: "600", flex: "1" }}>{p.project}</span>
              <span style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "15px", fontWeight: "600" }}>
                {p.value}
              </span>
              <span
                style={{
                  fontSize: "10.5px",
                  fontWeight: "700",
                  letterSpacing: ".06em",
                  textTransform: "uppercase",
                  color: p.statusFg,
                }}
              >
                {p.status}
              </span>
            </div>
            <div style={{ fontSize: "11.5px", color: "#8a8474", marginTop: "4px" }}>
              Sent {p.date} · expires {p.expiry} · probability {p.prob}
            </div>
            <div style={{ display: "flex", gap: "7px", marginTop: "10px", flexWrap: "wrap" }}>
              {p.isDraft ? (
                <button
                  onClick={p.onSent}
                  style={{
                    border: "1px solid #0c1220",
                    background: "#0c1220",
                    color: "#fff",
                    borderRadius: "4px",
                    padding: "6px 11px",
                    fontSize: "11px",
                    fontWeight: "600",
                    cursor: "pointer",
                  }}
                  className="hover-bg-a8863d"
                >
                  Mark sent
                </button>
              ) : null}
              {p.canView ? (
                <button
                  onClick={p.onViewed}
                  style={{
                    border: "1px solid #e6e2d8",
                    background: "#fff",
                    borderRadius: "4px",
                    padding: "6px 11px",
                    fontSize: "11px",
                    cursor: "pointer",
                    color: "#3a3f48",
                  }}
                  className="hover-bg-f6f4ef"
                >
                  Mark viewed
                </button>
              ) : null}
              {p.canNegotiate ? (
                <button
                  onClick={p.onNegotiate}
                  style={{
                    border: "1px solid #e6e2d8",
                    background: "#fff",
                    borderRadius: "4px",
                    padding: "6px 11px",
                    fontSize: "11px",
                    cursor: "pointer",
                    color: "#3a3f48",
                  }}
                  className="hover-bg-f6f4ef"
                >
                  Move to negotiation →
                </button>
              ) : null}
              <button
                onClick={p.onRecordResponse}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "6px 11px",
                  fontSize: "11px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
                className="hover-bg-f6f4ef"
              >
                Record response →
              </button>
            </div>
          </div>
        ))}
        {v.sel?.noProposals ? (
          <div style={{ fontSize: "13px", color: "#8a8474", marginTop: "12px" }}>
            No proposal yet. Build it from the discovery findings and the recorded opportunity value.
          </div>
        ) : null}
        {v.sel?.editingProposal ? (
          <div
            style={{
              borderTop: "1px solid #f0ede4",
              marginTop: "14px",
              paddingTop: "14px",
              display: "grid",
              gridTemplateColumns: "1fr 1fr",
              gap: "12px",
            }}
          >
            <div style={{ gridColumn: "span 2" }}>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Project <span style={{ color: "#b0453c" }}>Required</span>
              </div>
              <input
                value={v.sel?.pProject?.val}
                onChange={v.sel?.pProject?.on}
                placeholder="e.g. Client load-tracking portal"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 12px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Value (ZAR) <span style={{ color: "#b0453c" }}>Required</span>
              </div>
              <input
                value={v.sel?.pValue?.val}
                onChange={v.sel?.pValue?.on}
                placeholder="350000"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 12px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Notes
              </div>
              <input
                value={v.sel?.pNotes?.val}
                onChange={v.sel?.pNotes?.on}
                placeholder="Phasing, deposit, sticking points"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 12px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div style={{ gridColumn: "span 2", display: "flex", gap: "10px", justifyContent: "flex-end" }}>
              <button
                onClick={v.sel?.onCancelEdit}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "9px 16px",
                  fontSize: "12.5px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
              >
                Cancel
              </button>
              <button
                onClick={v.sel?.onSaveProposal}
                style={{
                  background: "#0c1220",
                  color: "#fff",
                  border: "none",
                  borderRadius: "4px",
                  padding: "9px 18px",
                  fontSize: "12.5px",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                className="hover-bg-a8863d"
              >
                Save proposal
              </button>
            </div>
          </div>
        ) : null}
      </div>
    </>
  );
}
