// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function DetailResearch({ v }: { v: VM }) {
  return (
    <>
      <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "18px 20px" }}>
        <div
          style={{
            fontSize: "10.5px",
            letterSpacing: ".12em",
            textTransform: "uppercase",
            color: "#a8863d",
            fontWeight: "600",
          }}
        >
          Research this company
        </div>
        <div style={{ fontSize: "13px", color: "#6b6f78", marginTop: "6px" }}>
          Review the company, website, services, market presence and digital experience.
        </div>
        {v.sel?.editingResearch ? (
          <div style={{ marginTop: "14px", display: "flex", flexDirection: "column", gap: "12px" }}>
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Summary <span style={{ color: "#b0453c" }}>Required</span>
              </div>
              <textarea
                value={v.sel?.rSummary?.val}
                onChange={v.sel?.rSummary?.on}
                placeholder="What does this company do, and why might they need AX-Channels?"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "10px 12px",
                  fontSize: "13px",
                  minHeight: "76px",
                  resize: "vertical",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Findings
              </div>
              <textarea
                value={v.sel?.rFindings?.val}
                onChange={v.sel?.rFindings?.on}
                placeholder="Services, market presence, size, recent news, anything that shapes the pitch."
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "10px 12px",
                  fontSize: "13px",
                  minHeight: "76px",
                  resize: "vertical",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Website
              </div>
              <input
                value={v.sel?.rWebsite?.val}
                onChange={v.sel?.rWebsite?.on}
                placeholder="company.co.za"
                style={{
                  width: "100%",
                  boxSizing: "border-box",
                  marginTop: "5px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "9px 12px",
                  fontSize: "13px",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
            <div style={{ display: "flex", gap: "10px", justifyContent: "flex-end" }}>
              <button
                onClick={v.sel?.onCancelEdit}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "9px 16px",
                  fontSize: "12.5px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
              >
                Cancel
              </button>
              <button
                onClick={v.sel?.onSaveResearch}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "9px 16px",
                  fontSize: "12.5px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
                className="hover-bg-f6f4ef"
              >
                Save draft
              </button>
              <button
                onClick={v.sel?.onCompleteResearch}
                style={{
                  background: "#0c1220",
                  color: "#fff",
                  border: "none",
                  borderRadius: "4px",
                  padding: "9px 18px",
                  fontSize: "12.5px",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                className="hover-bg-a8863d"
              >
                Mark research complete
              </button>
            </div>
          </div>
        ) : null}
        <div style={{ marginTop: "14px", display: v.sel?.researchViewDisplay }}>
          {v.sel?.researchEmpty ? (
            <div style={{ fontSize: "13px", color: "#8a8474" }}>
              No research yet. Start by documenting what you found about the company.
            </div>
          ) : null}
          {v.sel?.researchSummary ? (
            <>
              <div style={{ fontSize: "13.5px", lineHeight: "1.55", color: "#10151e" }}>{v.sel?.researchSummary}</div>
              <div style={{ fontSize: "13px", lineHeight: "1.55", color: "#6b6f78", marginTop: "8px" }}>
                {v.sel?.researchFindings}
              </div>
            </>
          ) : null}
          <button
            onClick={v.sel?.onStartResearch}
            style={{
              marginTop: "14px",
              background: "#0c1220",
              color: "#fff",
              border: "none",
              borderRadius: "4px",
              padding: "9px 18px",
              fontSize: "12.5px",
              fontWeight: "600",
              cursor: "pointer",
            }}
            className="hover-bg-a8863d"
          >
            {v.sel?.researchCta}
          </button>
        </div>
      </div>
    </>
  );
}
