// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function DetailFollowUp({ v }: { v: VM }) {
  return (
    <>
      <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "16px 20px" }}>
        <div
          style={{
            fontSize: "10.5px",
            letterSpacing: ".12em",
            textTransform: "uppercase",
            color: "#a8863d",
            fontWeight: "600",
          }}
        >
          Follow-up cadence
        </div>
        <div style={{ fontSize: "13px", color: "#6b6f78", marginTop: "6px" }}>
          Touch 1 initial observation · Touch 2 new value · Touch 3 proof or concept · Touch 4 close the loop. Use the
          buttons on each touch above to complete, reschedule or skip.
        </div>
        {v.sel?.noOutreachItems ? (
          <>
            <div style={{ fontSize: "13px", color: "#8a8474", marginTop: "10px" }}>
              Nothing to follow up yet — send the first touch first.
            </div>
            <button
              onClick={v.sel?.onGenerate}
              style={{
                marginTop: "10px",
                background: "#0c1220",
                color: "#fff",
                border: "none",
                borderRadius: "4px",
                padding: "8px 16px",
                fontSize: "12px",
                fontWeight: "600",
                cursor: "pointer",
              }}
              className="hover-bg-a8863d"
            >
              Generate outreach →
            </button>
          </>
        ) : null}
      </div>
    </>
  );
}
