// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";
import AddProspectModal from "./AddProspectModal";
import AnalyticsView from "./AnalyticsView";
import CampaignsView from "./CampaignsView";
import ClientsView from "./ClientsView";
import CloseOutcomeModal from "./CloseOutcomeModal";
import DashboardView from "./DashboardView";
import MessageGeneratorModal from "./MessageGeneratorModal";
import OpportunitiesView from "./OpportunitiesView";
import OpportunityBriefModal from "./OpportunityBriefModal";
import OutreachView from "./OutreachView";
import PipelineView from "./PipelineView";
import ProspectDetailView from "./ProspectDetailView";
import ProspectsView from "./ProspectsView";
import QueueView from "./QueueView";
import RecordResponseModal from "./RecordResponseModal";
import ScoreBreakdownModal from "./ScoreBreakdownModal";
import SettingsView from "./SettingsView";
import Sidebar from "./Sidebar";
import TasksView from "./TasksView";
import TemplatesView from "./TemplatesView";
import Topbar from "./Topbar";

export default function Layout({ v }: { v: VM }) {
  return (
    <>
      <div data-audit={v.audit} style={{ display: "flex", height: "100vh", overflow: "hidden", background: "#f6f4ef" }}>
        {/* Sidebar */}
        <Sidebar v={v} />
        {/* Main */}
        <div style={{ flex: "1", display: "flex", flexDirection: "column", minWidth: "0" }}>
          {/* Topbar */}
          <Topbar v={v} />
          {/* Content */}
          <div style={{ flex: "1", overflowY: "auto", padding: "24px" }}>
            {/* Dashboard */}
            {v.isDash ? <DashboardView v={v} /> : null}
            {/* Priority Queue */}
            {v.isQueue ? <QueueView v={v} /> : null}
            {/* Campaigns */}
            {v.isCampaigns ? <CampaignsView v={v} /> : null}
            {/* Prospects List */}
            {v.isProspects ? <ProspectsView v={v} /> : null}
            {/* Prospect Detail */}
            {v.isDetail ? <ProspectDetailView v={v} /> : null}
            {/* Opportunities */}
            {v.isOpps ? <OpportunitiesView v={v} /> : null}
            {/* Outreach */}
            {v.isOutreach ? <OutreachView v={v} /> : null}
            {/* Pipeline */}
            {v.isPipeline ? <PipelineView v={v} /> : null}
            {/* Clients */}
            {v.isClients ? <ClientsView v={v} /> : null}
            {/* Tasks */}
            {v.isTasks ? <TasksView v={v} /> : null}
            {/* Analytics */}
            {v.isAnalytics ? <AnalyticsView v={v} /> : null}
            {/* Templates */}
            {v.isTemplates ? <TemplatesView v={v} /> : null}
            {/* Settings */}
            {v.isSettings ? <SettingsView v={v} /> : null}
          </div>
        </div>
      </div>
      {/* Record Response */}
      {v.showOutcome ? <RecordResponseModal v={v} /> : null}
      {/* Close Won / Lost */}
      {v.showClose ? <CloseOutcomeModal v={v} /> : null}
      {/* Acquisition Score Breakdown */}
      {v.showScore ? <ScoreBreakdownModal v={v} /> : null}
      {/* Message Generator */}
      {v.showGen ? <MessageGeneratorModal v={v} /> : null}
      {/* Add Prospect Modal */}
      {v.showAdd ? <AddProspectModal v={v} /> : null}
      {/* Opportunity Brief Modal */}
      {v.showBrief ? <OpportunityBriefModal v={v} /> : null}
    </>
  );
}
