// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function MessageGeneratorModal({ v }: { v: VM }) {
  return (
    <>
      <div
        style={{
          position: "fixed",
          inset: "0",
          background: "rgba(12,18,32,.55)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          zIndex: "110",
        }}
      >
        <div style={{ background: "#fff", borderRadius: "8px", width: "700px", maxHeight: "90vh", overflowY: "auto" }}>
          <div
            style={{
              background: "#0c1220",
              color: "#fff",
              padding: "20px 26px",
              borderRadius: "8px 8px 0 0",
              display: "flex",
              justifyContent: "space-between",
              alignItems: "baseline",
            }}
          >
            <div>
              <div
                style={{
                  fontSize: "10px",
                  letterSpacing: ".16em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "700",
                }}
              >
                Personalised outreach · generated from recorded intelligence
              </div>
              <div
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "21px",
                  fontWeight: "600",
                  marginTop: "5px",
                }}
              >
                {v.genCompany}
              </div>
            </div>
            <div
              onClick={v.closeGen}
              style={{ fontSize: "13px", color: "rgba(255,255,255,.6)", cursor: "pointer" }}
              className="hover-color-fff"
            >
              Close ×
            </div>
          </div>
          {v.genLoading ? (
            <div style={{ padding: "52px 26px", textAlign: "center" }}>
              <div
                style={{
                  fontSize: "12px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "600",
                }}
              >
                Drafting from opportunity data…
              </div>
              <div style={{ fontSize: "12.5px", color: "#8a8474", marginTop: "8px" }}>
                Simulated generation — uses the company, contact, scan evidence and strategy on file
              </div>
            </div>
          ) : null}
          {v.genReady ? (
            <div style={{ padding: "18px 26px 24px 26px" }}>
              <div
                style={{
                  background: "#faf9f5",
                  border: "1px solid #e6e2d8",
                  borderRadius: "5px",
                  padding: "12px 14px",
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  gap: "8px 20px",
                }}
              >
                {v.genContext?.map((c, i) => (
                  <div key={i} style={{ fontSize: "12.5px", color: "#3a3f48" }}>
                    <span style={{ color: "#8a8474" }}>{c.k} · </span>
                    {c.v}
                  </div>
                ))}
              </div>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  marginTop: "12px",
                  background: v.genReadyFg,
                  borderRadius: "4px",
                  padding: "8px 12px",
                }}
              >
                <span
                  style={{
                    fontSize: "11.5px",
                    letterSpacing: ".1em",
                    textTransform: "uppercase",
                    fontWeight: "700",
                    color: "#fff",
                  }}
                >
                  {v.genReadyState}
                </span>
                {v.genHasMissing ? (
                  <span style={{ fontSize: "11.5px", color: "rgba(255,255,255,.9)" }}>
                    Missing:{" "}
                    {v.genReadyMissing?.map((m, i) => (
                      <span key={i} style={{ marginLeft: "6px" }}>
                        {m}
                      </span>
                    ))}
                  </span>
                ) : null}
              </div>
              <div style={{ display: "flex", gap: "8px", marginTop: "14px" }}>
                {v.genVariants?.map((v, i) => (
                  <div
                    key={i}
                    onClick={v.on}
                    style={{
                      fontSize: "12.5px",
                      padding: "7px 14px",
                      borderRadius: "4px",
                      cursor: "pointer",
                      fontWeight: "600",
                      border: "1px solid #e6e2d8",
                      background: v.bg,
                      color: v.fg,
                    }}
                  >
                    {v.label}
                  </div>
                ))}
              </div>
              <div style={{ fontSize: "11.5px", color: "#8a8474", marginTop: "10px" }}>{v.genNote}</div>
              {v.genPreviewing ? (
                <div
                  style={{
                    border: "1px solid #e6e2d8",
                    borderRadius: "5px",
                    padding: "16px 18px",
                    marginTop: "8px",
                    fontSize: "13.5px",
                    lineHeight: "1.65",
                    whiteSpace: "pre-wrap",
                    color: "#10151e",
                    background: "#fff",
                  }}
                >
                  {v.genBody}
                </div>
              ) : null}
              {v.genEditing ? (
                <textarea
                  value={v.genBody}
                  onChange={v.genSetBody}
                  style={{
                    width: "100%",
                    boxSizing: "border-box",
                    border: "1px solid #a8863d",
                    borderRadius: "5px",
                    padding: "16px 18px",
                    marginTop: "8px",
                    fontSize: "13.5px",
                    lineHeight: "1.65",
                    minHeight: "220px",
                    resize: "vertical",
                    color: "#10151e",
                    background: "#fff",
                    outline: "none",
                  }}
                />
              ) : null}
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  gap: "8px 20px",
                  marginTop: "12px",
                  background: "#faf9f5",
                  border: "1px solid #e6e2d8",
                  borderRadius: "5px",
                  padding: "12px 14px",
                }}
              >
                <div style={{ fontSize: "12.5px", color: "#3a3f48" }}>
                  <span style={{ color: "#8a8474" }}>Channel · </span>
                  {v.genChannel}
                </div>
                <div style={{ fontSize: "12.5px", color: "#3a3f48" }}>
                  <span style={{ color: "#8a8474" }}>CTA · </span>
                  {v.genCta}
                </div>
                <div style={{ fontSize: "12.5px", color: "#3a3f48" }}>
                  <span style={{ color: "#8a8474" }}>Follow-up date · </span>
                  {v.genFollowUpDate}
                </div>
                <div style={{ fontSize: "12.5px", color: "#3a3f48" }}>
                  <span style={{ color: "#8a8474" }}>On approve · </span>marks sent, creates the follow-up task
                </div>
              </div>
              <div style={{ display: "flex", gap: "10px", justifyContent: "flex-end", marginTop: "16px" }}>
                <button
                  onClick={v.genCopy}
                  style={{
                    border: "1px solid #e6e2d8",
                    background: "#fff",
                    borderRadius: "4px",
                    padding: "9px 16px",
                    fontSize: "13px",
                    cursor: "pointer",
                    color: "#3a3f48",
                  }}
                  className="hover-bg-f6f4ef"
                >
                  {v.genCopyLabel}
                </button>
                {v.genPreviewing ? (
                  <button
                    onClick={v.genOnEdit}
                    style={{
                      border: "1px solid #e6e2d8",
                      background: "#fff",
                      borderRadius: "4px",
                      padding: "9px 16px",
                      fontSize: "13px",
                      cursor: "pointer",
                      color: "#3a3f48",
                    }}
                    className="hover-bg-f6f4ef"
                  >
                    Edit
                  </button>
                ) : null}
                {v.genEditing ? (
                  <button
                    onClick={v.genDoneEdit}
                    style={{
                      border: "1px solid #a8863d",
                      background: "#fff",
                      borderRadius: "4px",
                      padding: "9px 16px",
                      fontSize: "13px",
                      cursor: "pointer",
                      color: "#7a5f24",
                      fontWeight: "600",
                    }}
                    className="hover-bg-f6f0e0"
                  >
                    Done editing
                  </button>
                ) : null}
                <button
                  onClick={v.genRegenerate}
                  style={{
                    border: "1px solid #e6e2d8",
                    background: "#fff",
                    borderRadius: "4px",
                    padding: "9px 16px",
                    fontSize: "13px",
                    cursor: "pointer",
                    color: "#3a3f48",
                  }}
                  className="hover-bg-f6f4ef"
                >
                  Regenerate
                </button>
                <button
                  onClick={v.genLog}
                  style={{
                    background: "#0c1220",
                    color: "#fff",
                    border: "none",
                    borderRadius: "4px",
                    padding: "9px 18px",
                    fontSize: "13px",
                    fontWeight: "600",
                    cursor: "pointer",
                  }}
                  className="hover-bg-a8863d"
                >
                  {"Approve & send"}
                </button>
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </>
  );
}
