// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";
import { activate } from "./ui";

export default function OpportunitiesView({ v }: { v: VM }) {
  return (
    <>
      <div style={{ display: "flex", gap: "8px", marginBottom: "14px" }}>
        {v.oppTabs?.map((t, i) => (
          <div
            key={i}
            onClick={t.on}
            style={{
              fontSize: "12.5px",
              padding: "7px 14px",
              borderRadius: "8px",
              cursor: "pointer",
              fontWeight: "600",
              border: "1px solid #e4e4e7",
              background: t.bg,
              color: t.fg,
            }}
            role="button"
            tabIndex={0}
            onKeyDown={activate}
          >
            {t.label}
          </div>
        ))}
      </div>
      {v.oppTabOpps ? (
        <>
          <div style={{ fontSize: "13px", color: "#697080", marginBottom: "14px" }}>
            Documented digital opportunities across the prospect base — total potential{" "}
            <span style={{ fontFamily: "'Archivo',system-ui,sans-serif", fontWeight: "600", color: "#0a0a0a" }}>
              {v.oppTotal}
            </span>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" }}>
            {v.opps?.map((o, i) => (
              <div
                key={i}
                onClick={o.on}
                style={{
                  background: "#fff",
                  border: "1px solid #e4e4e7",
                  borderRadius: "12px",
                  padding: "16px 18px",
                  cursor: "pointer",
                }}
                className="hover-border-a8863d"
                role="button"
                tabIndex={0}
                onKeyDown={activate}
              >
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
                  <span style={{ fontFamily: "'Archivo',system-ui,sans-serif", fontSize: "16px", fontWeight: "600" }}>
                    {o.company}
                  </span>
                  <span style={{ fontSize: "12px", color: "#73767a" }}>
                    Opp score{" "}
                    <span
                      style={{
                        fontFamily: "'Archivo',system-ui,sans-serif",
                        fontSize: "15px",
                        fontWeight: "600",
                        color: "#0a0a0a",
                      }}
                    >
                      {o.score}/25
                    </span>
                  </span>
                </div>
                <div style={{ fontSize: "13px", color: "#2a2c31", marginTop: "8px", lineHeight: "1.5" }}>{o.text}</div>
                <div style={{ display: "flex", gap: "6px", flexWrap: "wrap", marginTop: "10px" }}>
                  {o.problems?.map((pr, i) => (
                    <span
                      key={i}
                      style={{
                        fontSize: "11px",
                        background: "#fde8f1",
                        color: "#b3105a",
                        borderRadius: "999px",
                        padding: "3px 8px",
                      }}
                    >
                      {pr}
                    </span>
                  ))}
                </div>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    marginTop: "12px",
                    borderTop: "1px solid #efeff1",
                    paddingTop: "10px",
                  }}
                >
                  <span
                    style={{
                      fontSize: "11px",
                      letterSpacing: ".06em",
                      textTransform: "uppercase",
                      fontWeight: "700",
                      color: "#2a2c31",
                    }}
                  >
                    {o.service}
                  </span>
                  <span style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ fontSize: "11px", color: o.bandFg, fontWeight: "700" }}>{o.band}</span>
                    <span style={{ fontFamily: "'Archivo',system-ui,sans-serif", fontSize: "15px", fontWeight: "600" }}>
                      {o.value}
                    </span>
                  </span>
                </div>
                <div style={{ display: "flex", gap: "7px", marginTop: "12px", flexWrap: "wrap" }}>
                  <button
                    onClick={o.onCompany}
                    style={{
                      border: "1px solid #e4e4e7",
                      background: "#fff",
                      borderRadius: "8px",
                      padding: "6px 11px",
                      fontSize: "11px",
                      cursor: "pointer",
                      color: "#2a2c31",
                    }}
                    className="hover-bg-f6f4ef"
                  >
                    View company
                  </button>
                  <button
                    onClick={o.on}
                    style={{
                      border: "1px solid #e4e4e7",
                      background: "#fff",
                      borderRadius: "8px",
                      padding: "6px 11px",
                      fontSize: "11px",
                      cursor: "pointer",
                      color: "#2a2c31",
                    }}
                    className="hover-bg-f6f4ef"
                  >
                    Edit opportunity
                  </button>
                  <button
                    onClick={o.onStrategy}
                    style={{
                      border: "1px solid #e4e4e7",
                      background: "#fff",
                      borderRadius: "8px",
                      padding: "6px 11px",
                      fontSize: "11px",
                      cursor: "pointer",
                      color: "#2a2c31",
                    }}
                    className="hover-bg-f6f4ef"
                  >
                    Create strategy →
                  </button>
                  <button
                    onClick={o.onOutreach}
                    style={{
                      border: "1px solid #0a0a0a",
                      background: "#0a0a0a",
                      color: "#fff",
                      borderRadius: "8px",
                      padding: "6px 11px",
                      fontSize: "11px",
                      fontWeight: "600",
                      cursor: "pointer",
                    }}
                    className="hover-bg-a8863d"
                  >
                    Generate outreach →
                  </button>
                </div>
              </div>
            ))}
          </div>
          <div
            style={{
              background: "#fff",
              border: "1px solid #e4e4e7",
              borderRadius: "12px",
              marginTop: "16px",
              padding: "16px 20px",
            }}
          >
            <div
              style={{
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#e0176b",
                fontWeight: "600",
              }}
            >
              Opportunity types · AX-Channels service taxonomy
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "16px", marginTop: "14px" }}>
              {v.serviceTaxonomy?.map((g, i) => (
                <div key={i}>
                  <div
                    style={{
                      fontSize: "10px",
                      letterSpacing: ".1em",
                      textTransform: "uppercase",
                      color: "#2a2c31",
                      fontWeight: "700",
                      borderBottom: "1px solid #efeff1",
                      paddingBottom: "6px",
                    }}
                  >
                    {g.group}
                  </div>
                  {g.items?.map((i, idx) => (
                    <div
                      key={idx}
                      style={{
                        display: "flex",
                        justifyContent: "space-between",
                        fontSize: "12.5px",
                        padding: "5px 0",
                        color: "#697080",
                      }}
                    >
                      <span>{i.label}</span>
                      <span style={{ color: "#9a9ca3" }}>{i.count}</span>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
        </>
      ) : null}
      {v.oppTabScanner ? (
        <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
          {v.scanCompanies?.map((s, i) => (
            <div
              key={i}
              style={{ background: "#fff", border: "1px solid #e4e4e7", borderRadius: "12px", padding: "18px 20px" }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: "18px", flexWrap: "wrap" }}>
                <div style={{ flex: "1", minWidth: "200px" }}>
                  <div
                    onClick={s.on}
                    style={{
                      fontFamily: "'Archivo',system-ui,sans-serif",
                      fontSize: "18px",
                      fontWeight: "600",
                      cursor: "pointer",
                    }}
                    className="hover-color-a8863d"
                    role="button"
                    tabIndex={0}
                    onKeyDown={activate}
                  >
                    {s.name}
                  </div>
                  <div style={{ fontSize: "12px", color: "#73767a", marginTop: "2px" }}>{s.industry}</div>
                </div>
                <div style={{ textAlign: "right" }}>
                  <div
                    style={{
                      fontSize: "10px",
                      letterSpacing: ".12em",
                      textTransform: "uppercase",
                      color: "#73767a",
                      fontWeight: "700",
                    }}
                  >
                    Digital experience
                  </div>
                  <div
                    style={{
                      fontFamily: "'Archivo',system-ui,sans-serif",
                      fontSize: "24px",
                      fontWeight: "600",
                      color: s.dxFg,
                    }}
                  >
                    {s.dx}
                  </div>
                </div>
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "12px", marginTop: "14px" }}>
                {s.dims?.map((d, i) => (
                  <div key={i}>
                    <div style={{ display: "flex", justifyContent: "space-between", fontSize: "11.5px" }}>
                      <span style={{ color: "#697080" }}>{d.dim}</span>
                      <span style={{ fontWeight: "600", color: d.fg }}>{d.val}</span>
                    </div>
                    <div
                      style={{
                        background: "#efeff1",
                        borderRadius: "999px",
                        height: "5px",
                        marginTop: "4px",
                        position: "relative",
                      }}
                    >
                      <div
                        style={{
                          position: "absolute",
                          left: "0",
                          top: "0",
                          bottom: "0",
                          width: d.w,
                          background: d.bar,
                          borderRadius: "999px",
                        }}
                      />
                    </div>
                  </div>
                ))}
              </div>
              <div style={{ marginTop: "16px", borderTop: "1px solid #efeff1" }}>
                {s.scans?.map((r, i) => (
                  <div
                    key={i}
                    style={{
                      display: "grid",
                      gridTemplateColumns: "150px 90px 80px 1fr 1fr 1fr",
                      gap: "12px",
                      padding: "10px 0",
                      borderBottom: "1px solid #efeff1",
                      alignItems: "start",
                    }}
                  >
                    <span style={{ fontSize: "12.5px", fontWeight: "600" }}>{r.category}</span>
                    <span
                      style={{
                        fontSize: "11px",
                        fontWeight: "700",
                        letterSpacing: ".05em",
                        textTransform: "uppercase",
                        color: r.statusFg,
                      }}
                    >
                      {r.status}
                    </span>
                    <span
                      style={{
                        fontSize: "10px",
                        fontWeight: "700",
                        letterSpacing: ".05em",
                        textTransform: "uppercase",
                        color: "#fff",
                        background: r.sevFg,
                        borderRadius: "999px",
                        padding: "3px 6px",
                        textAlign: "center",
                      }}
                    >
                      {r.severity}
                    </span>
                    <span style={{ fontSize: "12px", color: "#2a2c31" }}>{r.problem}</span>
                    <span style={{ fontSize: "12px", color: "#73767a" }}>{r.evidence}</span>
                    <span style={{ fontSize: "12px", color: "#b3105a" }}>{r.opportunity}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
          <div style={{ background: "#fff", border: "1px dashed #d4d4d8", borderRadius: "12px", padding: "16px 20px" }}>
            <div
              style={{
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#b0453c",
                fontWeight: "700",
              }}
            >
              Not yet scanned
            </div>
            <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginTop: "10px" }}>
              {v.allScanned?.map((a, i) => (
                <span
                  key={i}
                  onClick={a.on}
                  style={{
                    fontSize: "12px",
                    border: "1px solid #e4e4e7",
                    borderRadius: "14px",
                    padding: "5px 12px",
                    cursor: "pointer",
                    background: "#fafafa",
                  }}
                  className="hover-border-a8863d"
                  role="button"
                  tabIndex={0}
                  onKeyDown={activate}
                >
                  {a.name}
                </span>
              ))}
            </div>
            {v.noUnscanned ? (
              <div style={{ fontSize: "12.5px", color: "#73767a", marginTop: "8px" }}>
                Every active prospect has a digital scan.
              </div>
            ) : null}
          </div>
        </div>
      ) : null}
      {v.oppTabMatrix ? (
        <>
          <div style={{ fontSize: "13px", color: "#697080", marginBottom: "14px" }}>
            Business impact against implementation complexity — what to pitch first.
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" }}>
            {v.matrix?.map((q, i) => (
              <div
                key={i}
                style={{
                  background: "#fff",
                  border: "1px solid #e4e4e7",
                  borderRadius: "12px",
                  padding: "16px 18px",
                  minHeight: "180px",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "baseline",
                    borderBottom: "1px solid #efeff1",
                    paddingBottom: "8px",
                  }}
                >
                  <span
                    style={{
                      fontSize: "13px",
                      fontWeight: "700",
                      letterSpacing: ".06em",
                      textTransform: "uppercase",
                      color: q.fg,
                    }}
                  >
                    {q.key}
                  </span>
                  <span style={{ fontSize: "11.5px", color: "#73767a" }}>{q.note}</span>
                </div>
                {q.items?.map((i, idx) => (
                  <div
                    key={idx}
                    onClick={i.on}
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "baseline",
                      gap: "10px",
                      padding: "9px 0",
                      borderBottom: "1px solid #efeff1",
                      cursor: "pointer",
                    }}
                    className="hover-color-a8863d"
                    role="button"
                    tabIndex={0}
                    onKeyDown={activate}
                  >
                    <span style={{ flex: "1" }}>
                      <span style={{ display: "block", fontSize: "13px", fontWeight: "500" }}>{i.company}</span>
                      <span style={{ display: "block", fontSize: "12px", color: "#73767a", marginTop: "1px" }}>
                        {i.type}
                      </span>
                    </span>
                    <span style={{ fontSize: "11.5px", color: "#73767a" }}>{i.score}</span>
                    <span style={{ fontFamily: "'Archivo',system-ui,sans-serif", fontSize: "14px", fontWeight: "600" }}>
                      {i.value}
                    </span>
                  </div>
                ))}
                {q.empty ? (
                  <div style={{ fontSize: "12.5px", color: "#9a9ca3", marginTop: "10px" }}>
                    Nothing in this quadrant.
                  </div>
                ) : null}
              </div>
            ))}
          </div>
        </>
      ) : null}
    </>
  );
}
