// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function OpportunityBriefModal({ v }: { v: VM }) {
  return (
    <>
      <div
        style={{
          position: "fixed",
          inset: "0",
          background: "rgba(12,18,32,.55)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          zIndex: "100",
        }}
      >
        <div style={{ background: "#fff", borderRadius: "8px", width: "640px", maxHeight: "88vh", overflowY: "auto" }}>
          <div
            style={{
              background: "#0c1220",
              color: "#fff",
              padding: "20px 26px",
              borderRadius: "8px 8px 0 0",
              display: "flex",
              justifyContent: "space-between",
              alignItems: "baseline",
            }}
          >
            <div>
              <div
                style={{
                  fontSize: "10px",
                  letterSpacing: ".16em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "700",
                }}
              >
                Digital opportunity brief · internal
              </div>
              <div
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "21px",
                  fontWeight: "600",
                  marginTop: "5px",
                }}
              >
                {v.briefCompany}
              </div>
            </div>
            <div
              onClick={v.closeBrief}
              style={{ fontSize: "13px", color: "rgba(255,255,255,.6)", cursor: "pointer" }}
              className="hover-color-fff"
            >
              Close ×
            </div>
          </div>
          {v.briefLoading ? (
            <div style={{ padding: "48px 26px", textAlign: "center" }}>
              <div
                style={{
                  fontSize: "12px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "600",
                }}
              >
                Generating brief…
              </div>
              <div style={{ fontSize: "12.5px", color: "#8a8474", marginTop: "8px" }}>
                Mock AI — assembling from recorded opportunity data
              </div>
            </div>
          ) : null}
          {v.briefReady ? (
            <div style={{ padding: "8px 26px 24px 26px" }}>
              {v.brief?.map((b, i) => (
                <div key={i} style={{ padding: "14px 0", borderBottom: "1px solid #f0ede4" }}>
                  <div
                    style={{
                      fontSize: "10px",
                      letterSpacing: ".12em",
                      textTransform: "uppercase",
                      color: "#a8863d",
                      fontWeight: "700",
                    }}
                  >
                    {b.h}
                  </div>
                  <div
                    style={{
                      fontSize: "13.5px",
                      lineHeight: "1.6",
                      marginTop: "6px",
                      color: "#3a3f48",
                      whiteSpace: "pre-wrap",
                    }}
                  >
                    {b.t}
                  </div>
                </div>
              ))}
              <div style={{ fontSize: "11px", color: "#a39d8f", marginTop: "14px" }}>
                Placeholder generation — V2 will draft this with AI from live research.
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </>
  );
}
