// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";
import { activate } from "./ui";

export default function OutreachView({ v }: { v: VM }) {
  return (
    <>
      <div
        style={{
          background: "#0c1220",
          borderRadius: "6px",
          padding: "16px 20px",
          marginBottom: "16px",
          display: "flex",
          gap: "0",
          color: "#fff",
        }}
      >
        {v.cadence?.map((c, i) => (
          <div key={i} style={{ flex: "1", borderLeft: "1px solid rgba(255,255,255,.1)", padding: "0 16px" }}>
            <div
              style={{
                fontSize: "10px",
                letterSpacing: ".14em",
                textTransform: "uppercase",
                color: "#a8863d",
                fontWeight: "700",
              }}
            >
              {c.touch}
            </div>
            <div style={{ fontSize: "13px", marginTop: "4px" }}>{c.label}</div>
            <div style={{ fontSize: "11px", color: "rgba(255,255,255,.5)", marginTop: "2px" }}>{c.timing}</div>
          </div>
        ))}
      </div>
      <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", marginBottom: "16px" }}>
        <div
          style={{
            padding: "14px 18px",
            borderBottom: "1px solid #f0ede4",
            display: "flex",
            justifyContent: "space-between",
          }}
        >
          <span
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Follow-ups due today
          </span>
          <span style={{ fontSize: "11.5px", color: "#8a8474" }}>{v.dueCount} due</span>
        </div>
        {v.followUpsDue?.map((f, i) => (
          <div
            key={i}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "14px",
              padding: "12px 18px",
              borderBottom: "1px solid #f0ede4",
            }}
          >
            <div style={{ flex: "1", minWidth: "0" }}>
              <div
                onClick={f.onOpen}
                style={{ fontSize: "13.5px", fontWeight: "500", cursor: "pointer" }}
                className="hover-color-a8863d"
                role="button"
                tabIndex={0}
                onKeyDown={activate}
              >
                {f.company}
              </div>
              <div style={{ fontSize: "12px", color: "#8a8474", marginTop: "2px" }}>{f.detail}</div>
            </div>
            <button
              onClick={f.onDone}
              style={{
                border: "1px solid #2e7d5b",
                color: "#2e7d5b",
                background: "#fff",
                borderRadius: "4px",
                padding: "6px 12px",
                fontSize: "11.5px",
                fontWeight: "600",
                cursor: "pointer",
              }}
              className="hover-bg-e8f2ec"
            >
              Complete
            </button>
            <button
              onClick={f.onResched}
              style={{
                border: "1px solid #e6e2d8",
                color: "#3a3f48",
                background: "#fff",
                borderRadius: "4px",
                padding: "6px 12px",
                fontSize: "11.5px",
                cursor: "pointer",
              }}
              className="hover-bg-f6f4ef"
            >
              Reschedule +3d
            </button>
            <button
              onClick={f.onSkip}
              style={{
                border: "1px solid #e6e2d8",
                color: "#8a8474",
                background: "#fff",
                borderRadius: "4px",
                padding: "6px 12px",
                fontSize: "11.5px",
                cursor: "pointer",
              }}
              className="hover-bg-f6f4ef"
            >
              Skip
            </button>
          </div>
        ))}
        {v.noDue ? (
          <div style={{ padding: "14px 18px", fontSize: "12.5px", color: "#8a8474" }}>
            Nothing due today. Check upcoming follow-ups below.
          </div>
        ) : null}
      </div>
      <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", overflowX: "auto" }}>
        <div
          style={{
            padding: "14px 18px",
            borderBottom: "1px solid #f0ede4",
            fontSize: "10.5px",
            letterSpacing: ".12em",
            textTransform: "uppercase",
            color: "#a8863d",
            fontWeight: "600",
          }}
        >
          All outreach
        </div>
        {v.allOutreach?.map((o, i) => (
          <div
            key={i}
            style={{
              display: "grid",
              gridTemplateColumns: "minmax(150px,1.6fr) 90px 60px minmax(200px,2.4fr) 90px 110px",
              gap: "10px",
              minWidth: "920px",
              padding: "11px 18px",
              borderBottom: "1px solid #f0ede4",
              alignItems: "center",
            }}
          >
            <span
              onClick={o.onOpen}
              style={{ fontSize: "13px", fontWeight: "500", cursor: "pointer" }}
              className="hover-color-a8863d"
              role="button"
              tabIndex={0}
              onKeyDown={activate}
            >
              {o.company}
            </span>
            <span
              style={{
                fontSize: "11px",
                letterSpacing: ".05em",
                textTransform: "uppercase",
                color: "#3a3f48",
                background: "#f0ede4",
                borderRadius: "3px",
                padding: "3px 6px",
                textAlign: "center",
              }}
            >
              {o.channel}
            </span>
            <span style={{ fontSize: "11.5px", color: "#8a8474" }}>{o.touchLabel}</span>
            <span style={{ fontSize: "12.5px", color: "#6b6f78" }}>{o.message}</span>
            <span style={{ fontSize: "11.5px", color: "#8a8474" }}>{o.date}</span>
            <span style={{ fontSize: "10.5px", fontWeight: "700", color: o.statusFg, textAlign: "right" }}>
              {o.status}
            </span>
          </div>
        ))}
      </div>
    </>
  );
}
