// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function PipelineView({ v }: { v: VM }) {
  return (
    <>
      <div style={{ display: "flex", gap: "8px", marginBottom: "16px", alignItems: "center" }}>
        <div
          onClick={v.setTabBoard}
          style={{
            fontSize: "12.5px",
            padding: "7px 14px",
            borderRadius: "4px",
            cursor: "pointer",
            fontWeight: "600",
            background: v.tabBoardBg,
            color: v.tabBoardFg,
            border: "1px solid #e6e2d8",
          }}
        >
          Board
        </div>
        <div
          onClick={v.setTabProps}
          style={{
            fontSize: "12.5px",
            padding: "7px 14px",
            borderRadius: "4px",
            cursor: "pointer",
            fontWeight: "600",
            background: v.tabPropsBg,
            color: v.tabPropsFg,
            border: "1px solid #e6e2d8",
          }}
        >
          Proposals
        </div>
        <div style={{ flex: "1" }} />
        <div style={{ fontSize: "12px", color: "#8a8474" }}>Drag cards between stages</div>
      </div>
      {v.isBoard ? (
        <div
          style={{ display: "flex", gap: "12px", overflowX: "auto", alignItems: "flex-start", paddingBottom: "12px" }}
        >
          {v.cols?.map((col, i) => (
            <div
              key={i}
              onDragOver={v.allowDrop}
              onDrop={col.onDrop}
              style={{
                width: "216px",
                flex: "none",
                background: "#efece4",
                borderRadius: "6px",
                padding: "10px",
                minHeight: "220px",
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "baseline",
                  padding: "2px 4px 10px 4px",
                }}
              >
                <span
                  style={{
                    fontSize: "10.5px",
                    letterSpacing: ".1em",
                    textTransform: "uppercase",
                    fontWeight: "700",
                    color: col.fg,
                  }}
                >
                  {col.name}
                </span>
                <span style={{ fontSize: "11px", color: "#8a8474" }}>
                  {col.count} · {col.total}
                </span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                {col.cards?.map((card, i) => (
                  <div
                    key={i}
                    draggable={true}
                    onDragStart={card.onDrag}
                    onClick={card.on}
                    style={{
                      background: "#fff",
                      border: "1px solid #e6e2d8",
                      borderRadius: "5px",
                      padding: "11px 12px",
                      cursor: "grab",
                    }}
                    className="hover-border-a8863d"
                  >
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: "8px" }}>
                      <span style={{ fontSize: "13px", fontWeight: "600" }}>{card.name}</span>
                      <span
                        style={{
                          width: "20px",
                          height: "20px",
                          borderRadius: "3px",
                          background: card.gradeBg,
                          color: card.gradeFg,
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontSize: "10.5px",
                          fontWeight: "700",
                          flex: "none",
                        }}
                      >
                        {card.grade}
                      </span>
                    </div>
                    <div style={{ fontSize: "11.5px", color: "#8a8474", marginTop: "4px" }}>{card.service}</div>
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "space-between",
                        marginTop: "8px",
                        alignItems: "baseline",
                      }}
                    >
                      <span
                        style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "13.5px", fontWeight: "600" }}
                      >
                        {card.value}
                      </span>
                      <span style={{ fontSize: "10.5px", color: card.dueFg }}>{card.due}</span>
                    </div>
                    <div
                      style={{
                        fontSize: "11.5px",
                        color: "#3a3f48",
                        marginTop: "6px",
                        borderTop: "1px solid #f0ede4",
                        paddingTop: "6px",
                      }}
                    >
                      {card.next}
                    </div>
                    {card.canConvert ? (
                      <button
                        onClick={card.onConvert}
                        style={{
                          marginTop: "8px",
                          width: "100%",
                          background: "#0c1220",
                          color: "#fff",
                          border: "none",
                          borderRadius: "4px",
                          padding: "7px 0",
                          fontSize: "11.5px",
                          fontWeight: "600",
                          cursor: "pointer",
                        }}
                        className="hover-bg-a8863d"
                      >
                        Convert to client
                      </button>
                    ) : null}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      ) : null}
      {v.isProps ? (
        <>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "12px", marginBottom: "16px" }}>
            <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "14px 16px" }}>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".12em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "600",
                }}
              >
                Open proposal value
              </div>
              <div
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "24px",
                  fontWeight: "600",
                  marginTop: "6px",
                }}
              >
                {v.pTotal}
              </div>
            </div>
            <div style={{ background: "#0c1220", borderRadius: "6px", padding: "14px 16px", color: "#fff" }}>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".12em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "600",
                }}
              >
                Weighted pipeline
              </div>
              <div
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "24px",
                  fontWeight: "600",
                  marginTop: "6px",
                }}
              >
                {v.wTotal}
              </div>
            </div>
            <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "14px 16px" }}>
              <div
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".12em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "600",
                }}
              >
                Accepted (won revenue)
              </div>
              <div
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "24px",
                  fontWeight: "600",
                  marginTop: "6px",
                  color: "#2e7d5b",
                }}
              >
                {v.wonTotal}
              </div>
            </div>
          </div>
          <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", overflowX: "auto" }}>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "minmax(150px,1.6fr) minmax(180px,2fr) 100px 90px 90px 100px 110px",
                gap: "10px",
                minWidth: "1040px",
                padding: "10px 18px",
                borderBottom: "1px solid #e6e2d8",
                background: "#faf9f5",
              }}
            >
              <span
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Prospect
              </span>
              <span
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Project
              </span>
              <span
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                  textAlign: "right",
                }}
              >
                Value
              </span>
              <span
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                  textAlign: "center",
                }}
              >
                Prob.
              </span>
              <span
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                  textAlign: "right",
                }}
              >
                Weighted
              </span>
              <span
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Expiry
              </span>
              <span
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                  textAlign: "right",
                }}
              >
                Status
              </span>
            </div>
            {v.proposals?.map((q, i) => (
              <div
                key={i}
                style={{
                  display: "grid",
                  gridTemplateColumns: "minmax(150px,1.6fr) minmax(180px,2fr) 100px 90px 90px 100px 110px",
                  gap: "10px",
                  minWidth: "1040px",
                  padding: "12px 18px",
                  borderBottom: "1px solid #f0ede4",
                  alignItems: "center",
                }}
              >
                <span
                  onClick={q.on}
                  style={{ fontSize: "13px", fontWeight: "500", cursor: "pointer" }}
                  className="hover-color-a8863d"
                >
                  {q.company}
                </span>
                <span style={{ fontSize: "12.5px", color: "#6b6f78" }}>{q.project}</span>
                <span
                  style={{
                    fontFamily: "'Source Serif 4',Georgia,serif",
                    fontSize: "13.5px",
                    fontWeight: "600",
                    textAlign: "right",
                  }}
                >
                  {q.value}
                </span>
                <span style={{ fontSize: "12.5px", textAlign: "center", color: "#6b6f78" }}>{q.prob}</span>
                <span
                  style={{
                    fontFamily: "'Source Serif 4',Georgia,serif",
                    fontSize: "13.5px",
                    fontWeight: "600",
                    textAlign: "right",
                    color: "#7a5f24",
                  }}
                >
                  {q.weighted}
                </span>
                <span style={{ fontSize: "12px", color: q.expiryFg }}>{q.expiry}</span>
                <span style={{ fontSize: "10.5px", fontWeight: "700", color: q.statusFg, textAlign: "right" }}>
                  {q.status}
                </span>
              </div>
            ))}
          </div>
        </>
      ) : null}
    </>
  );
}
