// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function ProspectsView({ v }: { v: VM }) {
  return (
    <>
      <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginBottom: "14px" }}>
        {v.savedViews?.map((v, i) => (
          <div
            key={i}
            onClick={v.on}
            style={{
              fontSize: "12px",
              padding: "6px 12px",
              borderRadius: "14px",
              cursor: "pointer",
              border: `1px solid ${v.border ?? ""}`,
              background: v.bg,
              color: v.fg,
            }}
            className="hover-border-a8863d"
          >
            {v.label}
          </div>
        ))}
      </div>
      <div style={{ display: "flex", gap: "10px", marginBottom: "14px", alignItems: "center" }}>
        <select
          value={v.fIndustry}
          onChange={v.setFIndustry}
          style={{
            border: "1px solid #e6e2d8",
            borderRadius: "4px",
            padding: "7px 10px",
            fontSize: "12.5px",
            background: "#fff",
            color: "#10151e",
          }}
        >
          {v.industryFilterOpts?.map((o, i) => (
            <option key={i} value={o}>
              {o}
            </option>
          ))}
        </select>
        <select
          value={v.fStage}
          onChange={v.setFStage}
          style={{
            border: "1px solid #e6e2d8",
            borderRadius: "4px",
            padding: "7px 10px",
            fontSize: "12.5px",
            background: "#fff",
            color: "#10151e",
          }}
        >
          {v.stageFilterOpts?.map((o, i) => (
            <option key={i} value={o}>
              {o}
            </option>
          ))}
        </select>
        <select
          value={v.fGrade}
          onChange={v.setFGrade}
          style={{
            border: "1px solid #e6e2d8",
            borderRadius: "4px",
            padding: "7px 10px",
            fontSize: "12.5px",
            background: "#fff",
            color: "#10151e",
          }}
        >
          {v.gradeFilterOpts?.map((o, i) => (
            <option key={i} value={o}>
              {o}
            </option>
          ))}
        </select>
        <select
          value={v.fSource}
          onChange={v.setFSource}
          style={{
            border: "1px solid #e6e2d8",
            borderRadius: "4px",
            padding: "7px 10px",
            fontSize: "12.5px",
            background: "#fff",
            color: "#10151e",
          }}
        >
          {v.sourceFilterOpts?.map((o, i) => (
            <option key={i} value={o}>
              {o}
            </option>
          ))}
        </select>
        <div onClick={v.clearFilters} style={{ fontSize: "12px", color: "#a8863d", cursor: "pointer" }}>
          Clear
        </div>
        <div style={{ flex: "1" }} />
        <div style={{ fontSize: "12.5px", color: "#8a8474" }}>{v.prospectCount} prospects</div>
      </div>
      <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", overflowX: "auto" }}>
        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "minmax(160px,1.7fr) 132px 70px minmax(130px,1.3fr) 92px minmax(100px,1fr) minmax(120px,1.2fr) minmax(140px,1.5fr) 70px",
            gap: "10px",
            minWidth: "1180px",
            padding: "10px 18px",
            borderBottom: "1px solid #e6e2d8",
            background: "#faf9f5",
          }}
        >
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
            }}
          >
            Company
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
            }}
          >
            Acquisition
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
            }}
          >
            Ready
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
            }}
          >
            Opportunity
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
              textAlign: "right",
            }}
          >
            Value
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
            }}
          >
            Stage
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
            }}
          >
            Decision-maker
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
            }}
          >
            Next best action
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
              textAlign: "right",
            }}
          >
            Due
          </span>
        </div>
        {v.prospects?.map((p, i) => (
          <div
            key={i}
            onClick={p.on}
            style={{
              display: "grid",
              gridTemplateColumns:
                "minmax(160px,1.7fr) 132px 70px minmax(130px,1.3fr) 92px minmax(100px,1fr) minmax(120px,1.2fr) minmax(140px,1.5fr) 70px",
              gap: "10px",
              minWidth: "1180px",
              padding: "12px 18px",
              borderBottom: "1px solid #f0ede4",
              cursor: "pointer",
              alignItems: "center",
            }}
            className="hover-bg-faf9f5"
          >
            <span>
              <span style={{ display: "block", fontSize: "13.5px", fontWeight: "500" }}>{p.name}</span>
              <span style={{ display: "block", fontSize: "11.5px", color: "#8a8474", marginTop: "1px" }}>
                {p.industry} <span style={{ color: "#b0453c", fontWeight: "600" }}>{p.stallLabel}</span>
              </span>
            </span>
            <span style={{ display: "flex", alignItems: "center", gap: "5px" }}>
              <span style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "15px", fontWeight: "600" }}>
                {p.acq}
              </span>
              <span
                style={{
                  fontSize: "9px",
                  letterSpacing: ".05em",
                  textTransform: "uppercase",
                  fontWeight: "700",
                  color: p.bandFg,
                  background: p.bandBg,
                  borderRadius: "3px",
                  padding: "2px 5px",
                }}
              >
                {p.band}
              </span>
            </span>
            <span style={{ fontSize: "12.5px", fontWeight: "700", color: p.readyFg }}>{p.readiness}</span>
            <span style={{ fontSize: "12.5px", color: "#6b6f78" }}>{p.opp}</span>
            <span
              style={{
                fontFamily: "'Source Serif 4',Georgia,serif",
                fontSize: "13.5px",
                fontWeight: "600",
                textAlign: "right",
              }}
            >
              {p.value}
            </span>
            <span>
              <span
                style={{
                  fontSize: "11px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "3px",
                  padding: "3px 8px",
                  color: "#3a3f48",
                  background: "#faf9f5",
                }}
              >
                {p.stage}
              </span>
            </span>
            <span style={{ fontSize: "12.5px", color: p.dmFg }}>{p.dm}</span>
            <span>
              <span style={{ display: "block", fontSize: "12.5px", color: "#10151e", fontWeight: "500" }}>
                {p.action}
              </span>
              <button
                onClick={p.onAction}
                style={{
                  marginTop: "4px",
                  border: "1px solid #0c1220",
                  background: "#0c1220",
                  color: "#fff",
                  borderRadius: "4px",
                  padding: "4px 9px",
                  fontSize: "10.5px",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                className="hover-bg-a8863d"
              >
                Go →
              </button>
            </span>
            <span style={{ fontSize: "11.5px", color: p.nextColor, textAlign: "right" }}>{p.due}</span>
          </div>
        ))}
      </div>
    </>
  );
}
