// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";
import { activate } from "./ui";

export default function QueueView({ v }: { v: VM }) {
  return (
    <>
      <div style={{ display: "flex", gap: "8px", alignItems: "center", marginBottom: "14px", flexWrap: "wrap" }}>
        <span style={{ fontSize: "12px", color: "#73767a", marginRight: "4px" }}>Sort by</span>
        {v.queueSorts?.map((s, i) => (
          <div
            key={i}
            onClick={s.on}
            style={{
              fontSize: "12px",
              padding: "6px 12px",
              borderRadius: "14px",
              cursor: "pointer",
              border: `1px solid ${s.border ?? ""}`,
              background: s.bg,
              color: s.fg,
            }}
            className="hover-border-a8863d"
            role="button"
            tabIndex={0}
            onKeyDown={activate}
          >
            {s.label}
          </div>
        ))}
        <div style={{ flex: "1" }} />
        <div style={{ fontSize: "12.5px", color: "#73767a" }}>
          {v.queueCount} active prospects · your daily working list
        </div>
      </div>
      <div style={{ background: "#fff", border: "1px solid #e4e4e7", borderRadius: "12px", overflowX: "auto" }}>
        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "40px minmax(150px,1.5fr) 138px 74px minmax(130px,1.3fr) 96px minmax(120px,1.2fr) minmax(130px,1.3fr) minmax(140px,1.4fr) 118px",
            gap: "10px",
            minWidth: "1240px",
            padding: "10px 18px",
            borderBottom: "1px solid #e4e4e7",
            background: "#fafafa",
          }}
        >
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#73767a",
              fontWeight: "700",
            }}
          >
            #
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#73767a",
              fontWeight: "700",
            }}
          >
            Company
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#73767a",
              fontWeight: "700",
            }}
          >
            Acquisition
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#73767a",
              fontWeight: "700",
            }}
          >
            Readiness
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#73767a",
              fontWeight: "700",
            }}
          >
            Opportunity
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#73767a",
              fontWeight: "700",
              textAlign: "right",
            }}
          >
            Value
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#73767a",
              fontWeight: "700",
            }}
          >
            Stage · DM
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#73767a",
              fontWeight: "700",
            }}
          >
            Why now
          </span>
          <span
            style={{
              fontSize: "10px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#73767a",
              fontWeight: "700",
            }}
          >
            Action
          </span>
          <span />
        </div>
        {v.queue?.map((q, i) => (
          <div
            key={i}
            onClick={q.on}
            style={{
              display: "grid",
              gridTemplateColumns:
                "40px minmax(150px,1.5fr) 138px 74px minmax(130px,1.3fr) 96px minmax(120px,1.2fr) minmax(130px,1.3fr) minmax(140px,1.4fr) 118px",
              gap: "10px",
              minWidth: "1240px",
              padding: "12px 18px",
              borderBottom: "1px solid #efeff1",
              cursor: "pointer",
              alignItems: "center",
            }}
            className="hover-bg-faf9f5"
            role="button"
            tabIndex={0}
            onKeyDown={activate}
          >
            <span style={{ fontFamily: "'Archivo',system-ui,sans-serif", fontSize: "14px", color: "#9a9ca3" }}>
              {q.rank}
            </span>
            <span style={{ fontSize: "13.5px", fontWeight: "500" }}>{q.name}</span>
            <span onClick={q.onScore} style={{ cursor: "pointer" }} role="button" tabIndex={0} onKeyDown={activate}>
              {" "}
              <span style={{ display: "flex", alignItems: "center", gap: "6px" }}>
                <span style={{ fontFamily: "'Archivo',system-ui,sans-serif", fontSize: "15px", fontWeight: "600" }}>
                  {q.acq}
                </span>
                <span
                  style={{
                    fontSize: "9.5px",
                    letterSpacing: ".06em",
                    textTransform: "uppercase",
                    fontWeight: "700",
                    color: q.bandFg,
                    background: q.bandBg,
                    borderRadius: "999px",
                    padding: "2px 6px",
                  }}
                >
                  {q.band}
                </span>
              </span>{" "}
              <span
                style={{
                  display: "block",
                  background: "#efeff1",
                  borderRadius: "999px",
                  height: "4px",
                  marginTop: "5px",
                  position: "relative",
                }}
              >
                <span
                  style={{
                    position: "absolute",
                    left: "0",
                    top: "0",
                    bottom: "0",
                    width: q.w,
                    background: q.bandFg,
                    borderRadius: "999px",
                  }}
                />
              </span>{" "}
            </span>
            <span>
              {" "}
              <span style={{ display: "block", fontSize: "12.5px", fontWeight: "700", color: q.readyFg }}>
                {q.readiness}
              </span>{" "}
              <span
                style={{
                  display: "block",
                  background: "#efeff1",
                  borderRadius: "999px",
                  height: "4px",
                  marginTop: "4px",
                  position: "relative",
                }}
              >
                <span
                  style={{
                    position: "absolute",
                    left: "0",
                    top: "0",
                    bottom: "0",
                    width: q.readyW,
                    background: q.readyFg,
                    borderRadius: "999px",
                  }}
                />
              </span>{" "}
            </span>
            <span style={{ fontSize: "12.5px", color: "#697080" }}>{q.opp}</span>
            <span
              style={{
                fontFamily: "'Archivo',system-ui,sans-serif",
                fontSize: "13.5px",
                fontWeight: "600",
                textAlign: "right",
              }}
            >
              {q.value}
            </span>
            <span>
              <span style={{ display: "block", fontSize: "11.5px", color: "#2a2c31" }}>{q.stage}</span>
              <span style={{ display: "block", fontSize: "11.5px", color: q.dmFg, marginTop: "2px" }}>{q.dm}</span>
            </span>
            <span style={{ fontSize: "12px", color: "#b3105a" }}>{q.whyNow}</span>
            <span style={{ fontSize: "12.5px", color: "#0a0a0a", fontWeight: "500" }}>{q.action}</span>
            <button
              onClick={q.onAction}
              style={{
                border: "1px solid #0a0a0a",
                background: "#0a0a0a",
                color: "#fff",
                borderRadius: "8px",
                padding: "6px 8px",
                fontSize: "11px",
                fontWeight: "600",
                cursor: "pointer",
              }}
              className="hover-bg-a8863d"
            >
              {q.action} →
            </button>
          </div>
        ))}
      </div>
    </>
  );
}
