// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function RecordResponseModal({ v }: { v: VM }) {
  return (
    <>
      <div
        style={{
          position: "fixed",
          inset: "0",
          background: "rgba(12,18,32,.55)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          zIndex: "120",
        }}
      >
        <div
          style={{
            background: "#fff",
            borderRadius: "8px",
            width: "560px",
            maxHeight: "88vh",
            overflowY: "auto",
            padding: "24px 26px",
          }}
        >
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
            <div style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "20px", fontWeight: "600" }}>
              Record response
            </div>
            <div
              onClick={v.closeOutcome}
              style={{ fontSize: "13px", color: "#8a8474", cursor: "pointer" }}
              className="hover-color-10151e"
            >
              Close ×
            </div>
          </div>
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
              marginTop: "18px",
            }}
          >
            Outcome
          </div>
          <div style={{ display: "flex", gap: "7px", flexWrap: "wrap", marginTop: "8px" }}>
            {v.outcomeOpts?.map((o, i) => (
              <div
                key={i}
                onClick={o.on}
                style={{
                  fontSize: "12px",
                  padding: "6px 12px",
                  borderRadius: "14px",
                  cursor: "pointer",
                  border: "1px solid #e6e2d8",
                  background: o.bg,
                  color: o.fg,
                }}
                className="hover-border-a8863d"
              >
                {o.label}
              </div>
            ))}
          </div>
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".1em",
              textTransform: "uppercase",
              color: "#8a8474",
              fontWeight: "700",
              marginTop: "18px",
            }}
          >
            Response notes
          </div>
          <textarea
            value={v.outcomeNotes}
            onChange={v.setOutcomeNotes}
            placeholder="What did they actually say?"
            style={{
              width: "100%",
              boxSizing: "border-box",
              marginTop: "6px",
              border: "1px solid #e6e2d8",
              borderRadius: "4px",
              padding: "10px 12px",
              fontSize: "13px",
              minHeight: "76px",
              resize: "vertical",
              background: "#faf9f5",
              color: "#10151e",
              outline: "none",
            }}
          />
          <div style={{ background: "#f6f0e0", borderRadius: "4px", padding: "12px 14px", marginTop: "16px" }}>
            <div
              style={{
                fontSize: "10px",
                letterSpacing: ".1em",
                textTransform: "uppercase",
                color: "#7a5f24",
                fontWeight: "700",
              }}
            >
              Recommended next action
            </div>
            <div
              style={{
                fontFamily: "'Source Serif 4',Georgia,serif",
                fontSize: "17px",
                fontWeight: "600",
                marginTop: "3px",
              }}
            >
              {v.outcomeRec}
            </div>
            <div style={{ fontSize: "11.5px", color: "#7a5f24", marginTop: "4px" }}>
              Saving sets this as the prospect’s next action and creates a task.
            </div>
          </div>
          <div style={{ display: "flex", gap: "10px", justifyContent: "flex-end", marginTop: "18px" }}>
            <button
              onClick={v.closeOutcome}
              style={{
                border: "1px solid #e6e2d8",
                background: "#fff",
                borderRadius: "4px",
                padding: "9px 16px",
                fontSize: "13px",
                cursor: "pointer",
                color: "#3a3f48",
              }}
            >
              Cancel
            </button>
            <button
              onClick={v.saveOutcome}
              style={{
                background: "#0c1220",
                color: "#fff",
                border: "none",
                borderRadius: "4px",
                padding: "9px 18px",
                fontSize: "13px",
                fontWeight: "600",
                cursor: "pointer",
              }}
              className="hover-bg-a8863d"
            >
              Save outcome
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
