// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function ScoreBreakdownModal({ v }: { v: VM }) {
  return (
    <>
      <div
        style={{
          position: "fixed",
          inset: "0",
          background: "rgba(12,18,32,.55)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          zIndex: "110",
        }}
      >
        <div style={{ background: "#fff", borderRadius: "8px", width: "520px", maxHeight: "88vh", overflowY: "auto" }}>
          <div
            style={{
              background: "#0c1220",
              color: "#fff",
              padding: "20px 26px",
              borderRadius: "8px 8px 0 0",
              display: "flex",
              justifyContent: "space-between",
              alignItems: "baseline",
            }}
          >
            <div>
              <div
                style={{
                  fontSize: "10px",
                  letterSpacing: ".16em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "700",
                }}
              >
                Acquisition score breakdown
              </div>
              <div
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "21px",
                  fontWeight: "600",
                  marginTop: "5px",
                }}
              >
                {v.scoreCompany}
              </div>
            </div>
            <div
              onClick={v.closeScore}
              style={{ fontSize: "13px", color: "rgba(255,255,255,.6)", cursor: "pointer" }}
              className="hover-color-fff"
            >
              Close ×
            </div>
          </div>
          <div style={{ padding: "18px 26px 24px 26px" }}>
            {v.scoreParts?.map((p, i) => (
              <div key={i} style={{ padding: "9px 0", borderBottom: "1px solid #f0ede4" }}>
                <div style={{ display: "flex", justifyContent: "space-between", fontSize: "13px" }}>
                  <span style={{ color: "#3a3f48" }}>{p.label}</span>
                  <span style={{ fontWeight: "600" }}>{p.val}</span>
                </div>
                <div
                  style={{
                    background: "#f0ede4",
                    borderRadius: "2px",
                    height: "5px",
                    marginTop: "5px",
                    position: "relative",
                  }}
                >
                  <div
                    style={{
                      position: "absolute",
                      left: "0",
                      top: "0",
                      bottom: "0",
                      width: p.w,
                      background: p.bar,
                      borderRadius: "2px",
                    }}
                  />
                </div>
              </div>
            ))}
            <div
              style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginTop: "14px" }}
            >
              <span
                style={{
                  fontSize: "10.5px",
                  letterSpacing: ".12em",
                  textTransform: "uppercase",
                  color: "#8a8474",
                  fontWeight: "700",
                }}
              >
                Total
              </span>
              <span style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "28px", fontWeight: "600" }}>
                {v.scoreTotal}
              </span>
            </div>
            <div style={{ marginTop: "12px", borderTop: "1px solid #f0ede4", paddingTop: "12px" }}>
              <div
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "700",
                }}
              >
                Recommendation
              </div>
              <div
                style={{
                  fontFamily: "'Source Serif 4',Georgia,serif",
                  fontSize: "19px",
                  fontWeight: "600",
                  marginTop: "3px",
                  color: v.scoreBandFg,
                }}
              >
                {v.scoreBand}
              </div>
              <div
                style={{
                  fontSize: "10px",
                  letterSpacing: ".1em",
                  textTransform: "uppercase",
                  color: "#a8863d",
                  fontWeight: "700",
                  marginTop: "12px",
                }}
              >
                Reason
              </div>
              <div style={{ fontSize: "13.5px", lineHeight: "1.55", marginTop: "3px", color: "#3a3f48" }}>
                {v.scoreReason}
              </div>
            </div>
            <div style={{ fontSize: "11px", color: "#a39d8f", marginTop: "14px" }}>
              Bands: 80–100 Priority · 60–79 Pursue · 40–59 Nurture · 0–39 Low priority. The /25 lead and opportunity
              scores are unchanged and feed this total.
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
