// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function SettingsView({ v }: { v: VM }) {
  return (
    <>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", alignItems: "start" }}>
        <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "18px 20px" }}>
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Workspace
          </div>
          {v.settingsRows?.map((s, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                justifyContent: "space-between",
                padding: "11px 0",
                borderBottom: "1px solid #f0ede4",
                fontSize: "13px",
              }}
            >
              <span style={{ color: "#6b6f78" }}>{s.k}</span>
              <span style={{ fontWeight: "500" }}>{s.v}</span>
            </div>
          ))}
        </div>
        <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "18px 20px" }}>
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Daily acquisition targets
          </div>
          <div style={{ fontSize: "12px", color: "#8a8474", marginTop: "6px" }}>
            Operating targets, not quotas. They drive the dashboard progress bars.
          </div>
          {v.settingsTargets?.map((t, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                padding: "9px 0",
                borderBottom: "1px solid #f0ede4",
              }}
            >
              <span style={{ fontSize: "13px", color: "#3a3f48" }}>{t.label}</span>
              <input
                value={t.val}
                onChange={t.on}
                style={{
                  width: "64px",
                  border: "1px solid #e6e2d8",
                  borderRadius: "4px",
                  padding: "6px 9px",
                  fontSize: "13px",
                  textAlign: "right",
                  background: "#faf9f5",
                  color: "#10151e",
                  outline: "none",
                }}
              />
            </div>
          ))}
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginTop: "14px",
              borderTop: "1px solid #f0ede4",
              paddingTop: "14px",
            }}
          >
            <span>
              <span style={{ display: "block", fontSize: "13px", fontWeight: "600" }}>Reset demo data</span>
              <span style={{ display: "block", fontSize: "11.5px", color: "#8a8474", marginTop: "2px" }}>
                Restore the original demo state
              </span>
            </span>
            <button
              onClick={v.resetDemo}
              style={{
                border: "1px solid #e6e2d8",
                background: "#fff",
                color: "#8a3b34",
                borderRadius: "4px",
                padding: "8px 14px",
                fontSize: "12px",
                fontWeight: "600",
                cursor: "pointer",
              }}
              className="hover-bg-f6e6e4"
            >
              Reset
            </button>
          </div>
          {v.isDemo ? (
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                marginTop: "12px",
                borderTop: "1px solid #f0ede4",
                paddingTop: "12px",
              }}
            >
              <span>
                <span style={{ display: "block", fontSize: "13px", fontWeight: "600" }}>Start with real prospects</span>
                <span style={{ display: "block", fontSize: "11.5px", color: "#8a8474", marginTop: "2px" }}>
                  Remove all demo data so it never mixes with real companies
                </span>
              </span>
              <button
                onClick={v.clearDemo}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  color: "#8a3b34",
                  borderRadius: "4px",
                  padding: "8px 14px",
                  fontSize: "12px",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                className="hover-bg-f6e6e4"
              >
                Remove demo data
              </button>
            </div>
          ) : null}
        </div>
        <div
          style={{
            background: "#fff",
            border: "1px solid #e6e2d8",
            borderRadius: "6px",
            padding: "18px 20px",
            gridColumn: "span 2",
          }}
        >
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            Development · QA
          </div>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              padding: "11px 0",
              borderBottom: "1px solid #f0ede4",
            }}
          >
            <span>
              <span style={{ display: "block", fontSize: "13px", fontWeight: "600" }}>Interaction audit</span>
              <span style={{ display: "block", fontSize: "11.5px", color: "#8a8474", marginTop: "2px" }}>
                Outlines every interactive element so dead controls are obvious
              </span>
            </span>
            <button
              onClick={v.toggleAudit}
              style={{
                border: "1px solid #e6e2d8",
                background: v.auditBg,
                color: v.auditFg,
                borderRadius: "4px",
                padding: "8px 16px",
                fontSize: "12px",
                fontWeight: "600",
                cursor: "pointer",
              }}
            >
              {v.auditLabel}
            </button>
          </div>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "11px 0" }}>
            <span>
              <span style={{ display: "block", fontSize: "13px", fontWeight: "600" }}>Workflow test</span>
              <span style={{ display: "block", fontSize: "11.5px", color: "#8a8474", marginTop: "2px" }}>
                Runs new prospect → research → assessment → opportunity → decision-maker → strategy → outreach →
                response and checks each transition
              </span>
            </span>
            <span style={{ display: "flex", gap: "8px", flex: "none" }}>
              <button
                onClick={v.runTest}
                style={{
                  background: "#0c1220",
                  color: "#fff",
                  border: "none",
                  borderRadius: "4px",
                  padding: "8px 16px",
                  fontSize: "12px",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                className="hover-bg-a8863d"
              >
                Run test
              </button>
              <button
                onClick={v.clearTest}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "8px 14px",
                  fontSize: "12px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
                className="hover-bg-f6f4ef"
              >
                Clear test data
              </button>
            </span>
          </div>
          {v.testRan ? (
            <div style={{ borderTop: "1px solid #f0ede4", paddingTop: "12px" }}>
              <div style={{ fontSize: "12px", fontWeight: "700", color: "#3a3f48" }}>{v.testSummary}</div>
              {v.testLog?.map((t, i) => (
                <div
                  key={i}
                  style={{
                    display: "flex",
                    gap: "12px",
                    alignItems: "baseline",
                    padding: "6px 0",
                    borderBottom: "1px solid #f0ede4",
                  }}
                >
                  <span style={{ fontSize: "11.5px", fontWeight: "700", color: t.fg, width: "64px", flex: "none" }}>
                    {t.mark}
                  </span>
                  <span style={{ fontSize: "12.5px", flex: "1" }}>{t.name}</span>
                  <span style={{ fontSize: "11.5px", color: "#8a8474" }}>{t.note}</span>
                </div>
              ))}
            </div>
          ) : null}
        </div>
        <div style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "18px 20px" }}>
          <div
            style={{
              fontSize: "10.5px",
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "#a8863d",
              fontWeight: "600",
            }}
          >
            AI capabilities (planned)
          </div>
          {v.aiRows?.map((s, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                padding: "11px 0",
                borderBottom: "1px solid #f0ede4",
              }}
            >
              <span>
                <span style={{ display: "block", fontSize: "13px", fontWeight: "500" }}>{s.k}</span>
                <span style={{ display: "block", fontSize: "11.5px", color: "#8a8474", marginTop: "2px" }}>{s.d}</span>
              </span>
              <span
                style={{
                  fontSize: "10px",
                  letterSpacing: ".08em",
                  textTransform: "uppercase",
                  fontWeight: "700",
                  color: "#8a8474",
                  background: "#f0ede4",
                  borderRadius: "3px",
                  padding: "3px 8px",
                  flex: "none",
                }}
              >
                Not configured
              </span>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
