// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function Sidebar({ v }: { v: VM }) {
  return (
    <div
      style={{
        width: "230px",
        flex: "none",
        background: "#0c1220",
        color: "#e8e6e0",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <div style={{ padding: "22px 20px 18px 20px", borderBottom: "1px solid rgba(255,255,255,.08)" }}>
        <div
          style={{
            fontFamily: "'Source Serif 4',Georgia,serif",
            fontSize: "19px",
            fontWeight: "600",
            letterSpacing: ".01em",
            color: "#fff",
          }}
        >
          AX—Channels
        </div>
        <div
          style={{
            fontSize: "10px",
            letterSpacing: ".18em",
            textTransform: "uppercase",
            color: "#a8863d",
            marginTop: "5px",
          }}
        >
          Client Acquisition Engine
        </div>
      </div>
      <div
        style={{
          padding: "14px 10px",
          display: "flex",
          flexDirection: "column",
          gap: "2px",
          flex: "1",
          overflowY: "auto",
        }}
      >
        {v.nav?.map((n, i) => (
          <div
            key={i}
            onClick={n.on}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              padding: "8px 12px",
              borderRadius: "4px",
              cursor: "pointer",
              fontSize: "13.5px",
              color: n.color,
              background: n.bg,
              borderLeft: `2px solid ${n.edge ?? ""}`,
            }}
            className="hover-color-ffffff"
          >
            <span>{n.label}</span>
            {n.count ? (
              <span
                style={{
                  fontSize: "10.5px",
                  background: "#a8863d",
                  color: "#0c1220",
                  fontWeight: "700",
                  borderRadius: "9px",
                  padding: "1px 7px",
                }}
              >
                {n.count}
              </span>
            ) : null}
          </div>
        ))}
      </div>
      <div style={{ padding: "14px 20px", borderTop: "1px solid rgba(255,255,255,.08)" }}>
        <div
          style={{
            fontSize: "10px",
            letterSpacing: ".14em",
            textTransform: "uppercase",
            color: "rgba(255,255,255,.4)",
          }}
        >
          Signed in
        </div>
        <div style={{ fontSize: "13px", color: "#fff", marginTop: "4px" }}>Sipho M. · Business Dev</div>
        <div
          style={{
            marginTop: "10px",
            display: "inline-block",
            fontSize: "10px",
            letterSpacing: ".1em",
            textTransform: "uppercase",
            color: "#a8863d",
            border: "1px solid rgba(168,134,61,.45)",
            borderRadius: "3px",
            padding: "3px 8px",
          }}
        >
          {v.demoLabel}
        </div>
      </div>
    </div>
  );
}
