// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";
import { activate } from "./ui";

export default function TasksView({ v }: { v: VM }) {
  return (
    <>
      {v.taskGroups?.map((g, i) => (
        <div
          key={i}
          style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", marginBottom: "16px" }}
        >
          <div
            style={{
              padding: "13px 18px",
              borderBottom: "1px solid #f0ede4",
              display: "flex",
              justifyContent: "space-between",
            }}
          >
            <span
              style={{
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                fontWeight: "700",
                color: g.fg,
              }}
            >
              {g.label}
            </span>
            <span style={{ fontSize: "11.5px", color: "#8a8474" }}>{g.count}</span>
          </div>
          {g.items?.map((t, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                alignItems: "center",
                gap: "12px",
                padding: "11px 18px",
                borderBottom: "1px solid #f0ede4",
              }}
            >
              <span
                onClick={t.onDone}
                style={{
                  width: "17px",
                  height: "17px",
                  borderRadius: "9px",
                  border: `1.5px solid ${t.circleBorder ?? ""}`,
                  background: t.circleBg,
                  cursor: "pointer",
                  flex: "none",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontSize: "10px",
                  color: "#fff",
                }}
                className="hover-border-a8863d"
                role="button"
                tabIndex={0}
                onKeyDown={activate}
                aria-label={t.doneAria + ": " + t.title}
                title={t.doneAria}
              >
                {t.check}
              </span>
              <span style={{ flex: "1", fontSize: "13.5px", color: t.titleFg, textDecoration: t.deco }}>{t.title}</span>
              <span
                data-click="1"
                onClick={t.onOpen}
                style={{ fontSize: "12px", color: "#8a8474", cursor: "pointer", textDecoration: "underline" }}
                className="hover-color-a8863d"
                role="button"
                tabIndex={0}
                onKeyDown={activate}
              >
                {t.company}
              </span>
{t.canReschedule ? (
              <button
                onClick={t.onReschedule}
                style={{
                  border: "1px solid #e6e2d8",
                  background: "#fff",
                  borderRadius: "4px",
                  padding: "4px 9px",
                  fontSize: "10.5px",
                  cursor: "pointer",
                  color: "#3a3f48",
                }}
                className="hover-bg-f6f4ef"
              >
                +3d
              </button>
              ) : null}
              <span
                style={{
                  fontSize: "10px",
                  letterSpacing: ".06em",
                  textTransform: "uppercase",
                  fontWeight: "700",
                  color: "#3a3f48",
                  background: "#f0ede4",
                  borderRadius: "3px",
                  padding: "3px 7px",
                }}
              >
                {t.type}
              </span>
              <span
                style={{ fontSize: "11px", fontWeight: "700", color: t.prioFg, width: "52px", textAlign: "center" }}
              >
                {t.priority}
              </span>
              <span style={{ fontSize: "11.5px", color: t.dueFg, width: "64px", textAlign: "right" }}>{t.due}</span>
            </div>
          ))}
          {g.empty ? (
            <div style={{ padding: "12px 18px", fontSize: "12.5px", color: "#8a8474" }}>Nothing here.</div>
          ) : null}
        </div>
      ))}
    </>
  );
}
