// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function TemplatesView({ v }: { v: VM }) {
  return (
    <>
      <div style={{ display: "flex", gap: "8px", marginBottom: "6px", flexWrap: "wrap" }}>
        {v.tplCats?.map((c, i) => (
          <div
            key={i}
            onClick={c.on}
            style={{
              fontSize: "12px",
              padding: "6px 14px",
              borderRadius: "14px",
              cursor: "pointer",
              border: `1px solid ${c.border ?? ""}`,
              background: c.bg,
              color: c.fg,
            }}
            className="hover-border-a8863d"
          >
            {c.label}
          </div>
        ))}
      </div>
      <div style={{ fontSize: "12px", color: "#8a8474", margin: "10px 0 16px 0" }}>
        Variables:{" "}
        {v.tplVars?.map((v, i) => (
          <span
            key={i}
            style={{
              fontFamily: "ui-monospace,Menlo,monospace",
              fontSize: "11px",
              background: "#f0ede4",
              borderRadius: "3px",
              padding: "2px 6px",
              marginRight: "6px",
            }}
          >
            {v}
          </span>
        ))}
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" }}>
        {v.tpls?.map((t, i) => (
          <div
            key={i}
            style={{ background: "#fff", border: "1px solid #e6e2d8", borderRadius: "6px", padding: "16px 18px" }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <span style={{ fontSize: "14px", fontWeight: "600" }}>{t.name}</span>
              <span style={{ display: "flex", gap: "8px", alignItems: "center" }}>
                <span
                  style={{
                    fontSize: "10px",
                    letterSpacing: ".08em",
                    textTransform: "uppercase",
                    fontWeight: "700",
                    color: "#7a5f24",
                    background: "#f6f0e0",
                    borderRadius: "3px",
                    padding: "3px 8px",
                  }}
                >
                  {t.category}
                </span>
                <button
                  onClick={t.onCopy}
                  style={{
                    border: "1px solid #e6e2d8",
                    background: "#fff",
                    borderRadius: "4px",
                    padding: "5px 10px",
                    fontSize: "11px",
                    cursor: "pointer",
                    color: "#3a3f48",
                  }}
                  className="hover-bg-f6f4ef"
                >
                  {t.copyLabel}
                </button>
              </span>
            </div>
            <div
              style={{
                fontSize: "12.5px",
                lineHeight: "1.6",
                marginTop: "10px",
                color: "#3a3f48",
                whiteSpace: "pre-wrap",
                borderTop: "1px solid #f0ede4",
                paddingTop: "10px",
              }}
            >
              {t.body}
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
