// Markup ported 1:1 from project/CAE V2.5.1.dc.html (initially generated by scripts/convert-design.py).
import type { VM } from "../vm";

export default function Topbar({ v }: { v: VM }) {
  return (
    <div
      style={{
        height: "58px",
        flex: "none",
        background: "#fff",
        borderBottom: "1px solid #e6e2d8",
        display: "flex",
        alignItems: "center",
        gap: "16px",
        padding: "0 24px",
        position: "relative",
        zIndex: "30",
      }}
    >
      <div style={{ fontFamily: "'Source Serif 4',Georgia,serif", fontSize: "17px", fontWeight: "600" }}>
        {v.viewTitle}
      </div>
      <div style={{ flex: "1" }} />
      <div style={{ position: "relative", width: "300px" }}>
        <input
          value={v.search}
          onChange={v.setSearch}
          placeholder="Search companies, contacts…"
          style={{
            width: "100%",
            boxSizing: "border-box",
            border: "1px solid #e6e2d8",
            borderRadius: "4px",
            padding: "7px 12px",
            fontSize: "13px",
            background: "#f6f4ef",
            outline: "none",
            color: "#10151e",
          }}
        />
        {v.hasSearch ? (
          <div
            style={{
              position: "absolute",
              top: "38px",
              left: "0",
              right: "0",
              background: "#fff",
              border: "1px solid #e6e2d8",
              borderRadius: "5px",
              boxShadow: "0 8px 24px rgba(16,21,30,.08)",
              overflow: "hidden",
            }}
          >
            {v.searchResults?.map((r, i) => (
              <div
                key={i}
                onClick={r.on}
                style={{
                  padding: "9px 12px",
                  fontSize: "13px",
                  cursor: "pointer",
                  display: "flex",
                  justifyContent: "space-between",
                  borderBottom: "1px solid #f0ede4",
                }}
                className="hover-bg-f6f4ef"
              >
                <span style={{ fontWeight: "500" }}>{r.name}</span>
                <span style={{ color: "#8a8474", fontSize: "12px" }}>{r.meta}</span>
              </div>
            ))}
          </div>
        ) : null}
      </div>
      <div style={{ position: "relative" }}>
        <div
          onClick={v.toggleBell}
          style={{
            width: "34px",
            height: "34px",
            border: "1px solid #e6e2d8",
            borderRadius: "4px",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            cursor: "pointer",
            background: "#fff",
            position: "relative",
          }}
          className="hover-bg-f6f4ef"
        >
          <span style={{ fontSize: "15px" }}>◦</span>
          {v.bellCount ? (
            <span
              style={{
                position: "absolute",
                top: "-6px",
                right: "-6px",
                background: "#b0453c",
                color: "#fff",
                fontSize: "10px",
                fontWeight: "700",
                borderRadius: "9px",
                padding: "1px 5px",
              }}
            >
              {v.bellCount}
            </span>
          ) : null}
        </div>
        {v.showBell ? (
          <div
            style={{
              position: "absolute",
              top: "42px",
              right: "0",
              width: "330px",
              background: "#fff",
              border: "1px solid #e6e2d8",
              borderRadius: "6px",
              boxShadow: "0 10px 28px rgba(16,21,30,.1)",
              overflow: "hidden",
            }}
          >
            <div
              style={{
                padding: "10px 14px",
                fontSize: "10.5px",
                letterSpacing: ".12em",
                textTransform: "uppercase",
                color: "#8a8474",
                borderBottom: "1px solid #f0ede4",
              }}
            >
              Notifications
            </div>
            {v.bellItems?.map((b, i) => (
              <div
                key={i}
                onClick={b.on}
                style={{ padding: "10px 14px", borderBottom: "1px solid #f0ede4", cursor: "pointer" }}
                className="hover-bg-f6f4ef"
              >
                <div
                  style={{
                    fontSize: "10px",
                    letterSpacing: ".1em",
                    textTransform: "uppercase",
                    color: b.color,
                    fontWeight: "600",
                  }}
                >
                  {b.tag}
                </div>
                <div style={{ fontSize: "13px", marginTop: "3px", color: "#10151e" }}>{b.text}</div>
              </div>
            ))}
          </div>
        ) : null}
      </div>
      <button
        onClick={v.openAdd}
        style={{
          background: "#0c1220",
          color: "#fff",
          border: "none",
          borderRadius: "4px",
          padding: "9px 16px",
          fontSize: "13px",
          fontWeight: "500",
          cursor: "pointer",
        }}
        className="hover-bg-a8863d"
      >
        + Add prospect
      </button>
    </div>
  );
}
